/**
 * 节日种子数据生成器
 * 用法：node db/tools/generate-seed.mjs
 * 输出：db/init/02_seed.sql
 *
 * 每年维护：只需更新本文件中动态节日的日期（感恩节/复活节/斋月/排灯节等），
 * 重新执行即可生成新的初始化 SQL。
 *
 * 条目格式：
 * [中文名, 英文名, 2026-MM-DD, 2027-MM-DD, 区域, 简介, 运营建议, [[商品中文名, 英文关键词, 优先级], ...]]
 * - 简介：节日时间安排、家庭/街道场景布置、活动流程
 * - 每个节日至少 10 件商品；关键词中 {YEAR} 会被替换为对应年份
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const MIN_GOODS_PER_FESTIVAL = 10;

const FESTIVALS = [
  ['元旦', "New Year's Day", '01-01', '01-01', 'NA,EU,SEA,LATAM',
    '公历1月1日，全球多数地区的公共假日。庆祝从12月31日新年前夜开始：家庭用金色与黑色气球拱门、拉旗、LED灯串布置客厅，年轻人参加倒计时派对，佩戴新年眼镜与派对帽，午夜举杯后抛洒彩屑。1月1日多以家庭早午餐、观看新年游行和橄榄球碗赛为主。',
    '12月初即上架派对装饰与拍照道具；印有具体年份的眼镜、数字气球须在节前清完库存，避免跨年滞销，可与圣诞装饰做组合套装提客单。',
    [['新年气球拱门套装', 'new years balloon garland kit', 'P1'],
     ['新年眼镜', 'happy new year glasses {YEAR}', 'P1'],
     ['新年拉旗横幅', 'happy new year banner', 'P1'],
     ['新年派对帽', 'new years eve party hats', 'P2'],
     ['LED新年灯串', 'new year led string lights', 'P2'],
     ['金色纸屑气球', 'gold confetti balloons', 'P2'],
     ['新年主题桌布', 'new years tablecloth', 'P2'],
     ['塑料香槟杯', 'plastic champagne flutes party', 'P3'],
     ['拍照道具相框', 'new years photo booth props', 'P3'],
     ['新年倒计时挂钟', 'new year countdown clock', 'P3']]],

  ['三王节', 'Día de Reyes / Three Kings Day', '01-06', '01-06', 'LATAM,EU',
    '1月6日主显节，西班牙与拉美大部分地区的公共假日。节前夜儿童把鞋子放在门口或窗下，等待三位国王骑骆驼送来礼物；6日全家分食圆形国王面包（Rosca de Reyes），面包内藏小玩偶，吃到者要主持2月2日圣烛节聚会。家中与教堂布置三王、骆驼与伯利恒之星主题装饰。',
    '西语市场圣诞季最后一个礼品窗口，12月至1月初集中出单；皇冠、骆驼与伯利恒之星为差异化品类，国王面包配件（小塑料玩偶、包装盒）复购稳定。',
    [['三王节皇冠', 'three kings crown', 'P1'],
     ['骆驼毛绒玩偶', 'camel stuffed animal', 'P1'],
     ['三王节装饰套装', 'three kings day decorations', 'P1'],
     ['国王面包小玩偶', 'plastic baby king cake dolls', 'P2'],
     ['三王节贺卡', 'three kings day card', 'P2'],
     ['三王节气球', 'three kings balloons', 'P2'],
     ['三王节拉旗', 'reyes magos banner', 'P2'],
     ['三王节礼品袋', 'reyes magos gift bags', 'P3'],
     ['儿童三王服装', 'three kings costume kids', 'P3'],
     ['伯利恒星星星棒', 'nativity star wand', 'P3']]],

  ['马丁·路德·金纪念日', 'Martin Luther King Jr. Day', '01-19', '01-18', 'NA',
    '美国联邦假日，每年1月第三个星期一，纪念民权运动领袖马丁·路德·金。当天学校、教堂与社区中心举行演讲、朗诵与志愿服务，教室布置“我有一个梦想”主题墙报、和平鸽手工与多元文化横幅，各地也举办纪念游行与免费社区餐会。',
    '节日客单以学校教室装饰为主，1月上旬是采购高峰；多元文化、平权主题物料可与2月黑人历史月合并备货，拉长销售周期。',
    [['我有一个梦想海报', 'mlk i have a dream poster', 'P1'],
     ['多元文化教室横幅', 'diversity classroom banner', 'P1'],
     ['和平鸽挂件', 'peace dove decoration', 'P1'],
     ['纪念徽章', 'mlk button pin', 'P2'],
     ['教室主题墙报', 'mlk classroom decorations', 'P2'],
     ['黑人历史月公告栏装饰', 'black history bulletin board set', 'P2'],
     ['多元肤色手工纸', 'multicultural construction paper', 'P2'],
     ['平等主题贴纸', 'equality stickers kids', 'P3'],
     ['和平主题手链', 'peace sign bracelet', 'P3'],
     ['儿童民权绘本', 'mlk book for kids', 'P3']]],

  ['越南春节', 'Tết Nguyên Đán / Lunar New Year', '02-17', '02-06', 'SEA',
    '越南最重要的农历新年（2026年为2月17日），除夕至初五全国放假。节前家家户户大扫除、采购桃花枝（北部）与黄梅（南部）、摆放年橘盆景，大门贴红色春联与福字；除夕守岁、初一拜年发利是，供桌摆五果盘与粽子，街头挂满红灯笼与节日旗。',
    '红色年俗商品节前两周集中爆发，利是封、春联为走量爆款；桃花、年橘等大件适合本地海外仓，跨境卖家主推轻量化装饰与利是封。',
    [['越南春联', 'tet decorations', 'P1'],
     ['红色利是封', 'lucky money envelopes red', 'P1'],
     ['桃花枝装饰', 'hoa dao tet flowers', 'P1'],
     ['年橘盆景', 'kumquat bonsai', 'P2'],
     ['越南灯笼', 'vietnamese lanterns', 'P2'],
     ['春节福字对联', 'tet calligraphy couplets', 'P2'],
     ['春节鞭炮挂饰', 'tet firecrackers decoration', 'P2'],
     ['供桌五果盘', 'tet fruit tray', 'P3'],
     ['越南年历', 'vietnamese wall calendar', 'P3'],
     ['春节红包袋套装', 'tet li xi envelopes pack', 'P3']]],

  ['狂欢节（马迪格拉斯）', 'Mardi Gras / Carnival', '02-17', '02-09', 'EU',
    '圣灰星期三前的星期二（2026年为2月17日），欧洲狂欢季的收官日，新奥尔良有持续两周的游行季。街道与派对现场以紫金绿三色装饰，参加者佩戴面具、抛接珠链、挥舞羽毛披肩；花车游行沿途举办街区派对，国王饼是节令食品。',
    '装扮类商品节前两周集中爆发，面具与珠链是刚需消耗品，可多件装出售；紫金绿三色套装辨识度高，适合做组合包提客单。',
    [['狂欢节面具', 'mardi gras mask', 'P1'],
     ['紫金绿珠链', 'mardi gras beads', 'P1'],
     ['羽毛披肩', 'mardi gras feather boa', 'P1'],
     ['国王饼装饰', 'king cake decorations', 'P2'],
     ['紫金绿气球', 'mardi gras balloons', 'P2'],
     ['狂欢节拉旗', 'mardi gras banner', 'P2'],
     ['狂欢节套装', 'mardi gras outfit women', 'P2'],
     ['紫金绿桌布', 'mardi gras tablecloth', 'P3'],
     ['派对照相道具', 'mardi gras photo booth props', 'P3'],
     ['脸部闪粉贴纸', 'mardi gras face glitter', 'P3']]],

  ['巴西狂欢节', 'Rio Carnival', '02-13', '02-05', 'LATAM',
    '全球规模最大的狂欢节（2026年2月13日起，圣灰星期三前），里约桑巴大道举行通宵桑巴校队游行，全城举办街头Bloco街区派对。参与者身着羽毛头饰、亮片服饰，抛洒五彩纸屑，海岸城市同时结合沙滩派对，庆典持续约一周。',
    '羽毛头饰与桑巴服饰客单价高、重量轻，适合提前45天海运；亮片短裤、身体闪粉等配件可做多款组合，2月初为流量高峰。',
    [['桑巴羽毛头饰', 'brazil carnival headdress', 'P1'],
     ['狂欢节服装', 'brazil carnival costume', 'P1'],
     ['桑巴舞鞋', 'samba dance shoes', 'P2'],
     ['庆典五彩纸屑', 'carnival confetti', 'P2'],
     ['巴西国旗配饰', 'brazil flag accessories', 'P2'],
     ['羽毛披肩', 'carnival feather boa', 'P2'],
     ['桑巴亮片短裤', 'carnival sequin shorts', 'P3'],
     ['狂欢节面具', 'brazil carnival mask', 'P3'],
     ['身体闪粉亮片', 'carnival body glitter', 'P3'],
     ['派对喇叭哨子', 'party blowers horns', 'P3']]],

  ['情人节', "Valentine's Day", '02-14', '02-14', 'NA,EU,SEA',
    '2月14日，北美与欧洲的浪漫节日。2月上旬餐厅与酒店即被订满，家庭与求婚现场以红粉气球、爱心拉旗、仿真玫瑰花瓣布置餐桌与卧室；当天互赠鲜花、珠宝、巧克力与卡片，晚间多为烛光晚餐或周末短途旅行。',
    '提前一个月上架，1月下旬进入流量高峰；永生花、女士饰品为主推高客单，气球与派对装饰走量，注意贺卡文案无拼写错误以提高转化。',
    [['永生花礼盒', 'preserved rose gift', 'P1'],
     ['女士项链', 'valentines necklace for women', 'P1'],
     ['毛绒泰迪熊', 'valentines teddy bear', 'P1'],
     ['爱心气球', 'heart balloons', 'P1'],
     ['情人节礼品盒', 'valentines gift box', 'P2'],
     ['情人节拉旗', 'happy valentines day banner', 'P2'],
     ['仿真玫瑰花瓣', 'artificial rose petals', 'P2'],
     ['情侣对杯', 'valentines couple mugs', 'P2'],
     ['LED爱心灯串', 'heart fairy lights', 'P3'],
     ['情人节贺卡', 'valentines day card', 'P3']]],

  ['总统日', "Presidents' Day", '02-16', '02-15', 'NA',
    '美国联邦假日，每年2月第三个星期一，纪念乔治·华盛顿等历任总统。商场借长周末举办大促，学校教室布置总统主题墙报与认知卡片，红白蓝爱国装饰出现在社区活动中心，部分城市举办历史重演与纪念仪式。',
    '红白蓝主题装饰可与阵亡将士纪念日、独立日共用一套供应链；电商平台普遍有长周末促销，2月上旬备好库存蹭平台流量。',
    [['美国国旗', 'american flag 3x5', 'P1'],
     ['总统主题海报', 'presidents day poster', 'P1'],
     ['红白蓝装饰', 'red white blue decorations', 'P2'],
     ['总统认知卡片', 'presidents flash cards', 'P2'],
     ['教室主题装饰', 'presidents day classroom decorations', 'P2'],
     ['爱国花环', 'patriotic wreath', 'P2'],
     ['爱国徽章', 'patriotic button pins', 'P3'],
     ['儿童总统绘本', 'presidents book for kids', 'P3'],
     ['总统扮演道具币', 'presidents coins play money', 'P3'],
     ['投票主题贴纸', 'vote stickers kids', 'P3']]],

  ['斋月开始', 'Ramadan Begins', '02-18', '02-07', 'ME',
    '伊斯兰历九月斋月（2026年约2月18日开始），持续约30天。穆斯林白天斋戒、日落后开斋聚餐，家中以新月星星造型灯笼、串灯布置客厅与餐桌，门挂斋月标识；夜晚清真寺与商场灯火通明，家庭备椰枣、点心招待访客，最后十天还有夜间礼拜与寻找盖德尔夜的活动。',
    '斋月灯饰与家居装饰在中东爆发式增长，灯笼（Fanous）为标志性爆款；须提前45天备货，倒计时日历、桌旗等新品类竞争小、毛利高。',
    [['斋月灯笼', 'ramadan lantern', 'P1'],
     ['斋月倒计时日历', 'ramadan advent calendar', 'P1'],
     ['星月串灯', 'ramadan fairy lights', 'P1'],
     ['斋月桌旗', 'ramadan table runner', 'P1'],
     ['椰枣礼盒', 'dates gift box', 'P2'],
     ['斋月气球套装', 'ramadan balloons', 'P2'],
     ['斋月门挂牌', 'ramadan door sign', 'P2'],
     ['斋月餐盘餐具', 'ramadan plates napkins', 'P2'],
     ['礼拜垫', 'prayer mat islamic', 'P3'],
     ['斋月贺卡', 'ramadan mubarak card', 'P3']]],

  ['国际妇女节', "International Women's Day", '03-08', '03-08', 'EU,ME',
    '3月8日联合国纪念日，在东欧、中亚与俄语区是法定假日。当天男性向母亲、妻子与同事赠送郁金香、贺卡与礼盒，公司组织庆祝活动并发放礼品，餐厅推出节日套餐；街头花市从早晨开始排队，晚间多为家庭聚餐或演出。',
    '郁金香、贺卡与礼盒是主流，3月初进入高峰；中亚与俄罗斯市场客单可做高，丝巾、香水等实用礼品优于纯装饰。',
    [['仿真郁金香', 'artificial tulips', 'P1'],
     ['妇女节贺卡', 'womens day card', 'P1'],
     ['花束礼盒', 'flower gift box', 'P1'],
     ['女士丝巾', 'womens silk scarf', 'P2'],
     ['妇女节气球', 'womens day balloons', 'P2'],
     ['心形巧克力礼盒', 'heart chocolate box', 'P2'],
     ['女士香水礼盒', 'womens perfume gift set', 'P2'],
     ['SPA礼品篮', 'spa gift basket women', 'P3'],
     ['数字8气球', 'number 8 balloons', 'P3'],
     ['首饰收纳盒', 'jewelry box organizer', 'P3']]],

  ['圣帕特里克节', "St. Patrick's Day", '03-17', '03-17', 'NA',
    '3月17日爱尔兰传统宗教节日，在美国已演变为全民绿色狂欢。纽约、芝加哥等城市举行盛大游行，酒吧与派对现场以绿色三叶草装饰，参加者全身绿色装扮、佩戴珠链、饮用绿色啤酒；当天还有教堂礼拜与传统音乐节。',
    '绿色装扮是绝对主题，客单低但转化高，适合眼镜、袜子、项链等多件组合套装；3月上旬完成上架，酒吧周边用品需求集中。',
    [['三叶草眼镜', 'shamrock glasses', 'P1'],
     ['圣帕特里克装扮', 'st patricks day outfit', 'P1'],
     ['绿帽胡子套装', 'leprechaun hat beard', 'P1'],
     ['三叶草袜子', 'shamrock socks', 'P2'],
     ['爱尔兰国旗', 'ireland flag', 'P2'],
     ['三叶草珠链', 'shamrock necklace beads', 'P2'],
     ['圣帕特里克拉旗', 'st patricks day banner', 'P2'],
     ['绿色塑料啤酒杯', 'green plastic cups party', 'P3'],
     ['三叶草脸贴', 'shamrock stickers face', 'P3'],
     ['小矮妖摆件', 'leprechaun figurine', 'P3']]],

  ['英国母亲节', 'Mothering Sunday', '03-15', '03-07', 'EU',
    '英国母亲节为四旬期第四个星期日（2026年3月15日）。子女带母亲享用英式下午茶、赠送鲜花与贺卡，家中布置春季花卉；当天教堂举行探访母堂的传统礼拜，餐厅与茶室全部订满，商场推出下午茶礼盒与香薰礼品。',
    '注意与5月美国母亲节是两个日期，英国站需提前一个月单独备货；茶具、香薰蜡烛与鲜花包装为主推品类。',
    [['英式茶具套装', 'afternoon tea set', 'P1'],
     ['母亲节鲜花', 'mothers day flowers', 'P1'],
     ['母亲节贺卡', 'mothers day card uk', 'P1'],
     ['香薰蜡烛礼盒', 'scented candles gift set', 'P2'],
     ['西蒙蛋糕装饰', 'simnel cake decorations', 'P2'],
     ['花束包装纸', 'flower wrapping paper', 'P2'],
     ['女士家居睡袍', 'womens dressing gown', 'P2'],
     ['手工巧克力礼盒', 'handmade chocolates gift', 'P3'],
     ['下午茶点心架', 'cake stand afternoon tea', 'P3'],
     ['妈妈相框', 'mum photo frame gift', 'P3']]],

  ['诺鲁孜节', 'Nowruz', '03-20', '03-21', 'ME',
    '波斯历新年（春分前后，2026年3月20日），中亚五国、伊朗、阿富汗等地最重要的节日，持续约两周。家中郑重摆放“七鲜桌”（Haft Seen）：发芽小麦草、彩绘彩蛋、金鱼缸、风信子、蒜、苹果、醋等七样以S开头的物品；除夕阖家守岁，初一拜年发红包，节后第13天全家外出踏青。',
    '中亚市场全年最大消费节点，七鲜桌摆件与彩蛋套装为特色爆款；绿植、金鱼缸等场景商品可做套装，3月上旬完成上架。',
    [['七鲜桌摆件', 'haft seen set', 'P1'],
     ['彩绘彩蛋套装', 'nowruz painted eggs', 'P1'],
     ['发芽小麦草', 'sabzeh wheat grass kit', 'P1'],
     ['金鱼缸装饰', 'nowruz goldfish bowl', 'P2'],
     ['诺鲁孜贺卡', 'nowruz card', 'P2'],
     ['七鲜桌布', 'haft seen tablecloth', 'P2'],
     ['金币巧克力', 'nowruz gold coins chocolate', 'P2'],
     ['诺鲁孜拉旗', 'nowruz banner', 'P3'],
     ['风信子盆栽装饰', 'hyacinth artificial pot', 'P3'],
     ['儿童新年手工', 'nowruz crafts for kids', 'P3']]],

  ['开斋节', 'Eid al-Fitr / Hari Raya Aidilfitri', '03-20', '03-09', 'ME,SEA',
    '斋月结束的盛大节日（2026年3月20日），一般放假3天。节前家家户户大扫除、购置新衣与家居装饰，门上挂星月拉旗与气球；首日清晨参加会礼，之后走亲访友、给孩子发绿色红包封，餐桌摆满甜食与点心，互赠礼盒。',
    '节日服饰、礼盒与装饰三驾马车，节前两周集中出单；中东偏好华丽金色、东南亚偏好清新绿色，关键词共用但选品注意风格差异。',
    [['开斋节拉旗', 'eid mubarak banner', 'P1'],
     ['星月气球套装', 'eid balloons', 'P1'],
     ['开斋节礼品盒', 'eid gift boxes', 'P1'],
     ['贺卡红包封', 'eid money envelopes', 'P1'],
     ['节日餐具套装', 'eid tableware set', 'P2'],
     ['开斋节灯饰', 'eid lights decorations', 'P2'],
     ['男士节日服饰', 'eid clothes men', 'P2'],
     ['女士节日服饰', 'eid dress women', 'P2'],
     ['节日糖果盘', 'eid serving tray', 'P3'],
     ['开斋节贺卡', 'eid mubarak card', 'P3']]],

  ['复活节', 'Easter Sunday', '04-05', '03-28', 'NA,EU',
    '春分月圆后的第一个星期日（2026年4月5日）。家庭以彩蛋、兔子、小鸡与春季花卉布置客厅与餐桌，复活节前夕教堂举行守夜礼拜；周日早晨儿童挎着寻蛋篮在庭院或教堂草坪参加寻蛋活动，中午家庭聚餐，吃火腿、十字面包与彩蛋。',
    '彩蛋、兔子玩偶与寻蛋篮是儿童刚需；日期每年变动，须按当年日期倒推备货，染料套装、草丝等配件做组合可提客单。',
    [['复活节彩蛋', 'easter eggs plastic', 'P1'],
     ['兔子毛绒玩偶', 'stuffed bunny plush', 'P1'],
     ['寻蛋篮', 'easter basket', 'P1'],
     ['复活节装饰', 'easter decorations', 'P1'],
     ['兔耳发箍', 'bunny ears headband', 'P2'],
     ['复活节拉旗', 'happy easter banner', 'P2'],
     ['彩蛋染料套装', 'easter egg dye kit', 'P2'],
     ['复活节草丝', 'easter grass filler', 'P2'],
     ['寻蛋活动标识', 'easter egg hunt signs', 'P3'],
     ['小鸡毛绒摆件', 'easter chick decor', 'P3']]],

  ['宋干节（泼水节）', 'Songkran Festival', '04-13', '04-13', 'SEA',
    '泰国传统新年，4月13–15日全国放假。人们手持水枪、水桶在街头互相泼水祈福，前往寺庙浴佛、堆沙塔，向长辈洒水行礼；清迈、普吉、芭提雅同时迎来旅游高峰，游客穿着花衬衫、佩戴防水手机袋全天参与泼水。',
    '水枪与防水用品为绝对爆款，体积小重量轻适合空运快速补货；4月初即进入高峰，背包水枪与大容量水枪利润更高。',
    [['水枪', 'water gun soaker', 'P1'],
     ['防水手机袋', 'waterproof phone pouch', 'P1'],
     ['泼水节花衬衫', 'songkran shirt', 'P1'],
     ['防水干袋', 'waterproof dry bag', 'P2'],
     ['施水碗盆', 'songkran water bowl', 'P2'],
     ['防水腰包', 'waterproof waist bag', 'P2'],
     ['防水护目镜', 'water goggles swimming', 'P2'],
     ['背包水枪', 'backpack water gun kids', 'P3'],
     ['泼水节花环', 'songkran garland flowers', 'P3'],
     ['泰式保健粉', 'thanaka powder natural', 'P3']]],

  ['雄王祭祖日', "Hung Kings' Temple Festival", '04-26', '04-19', 'SEA',
    '越南农历三月初十（2026年4月26日）的国家级纪念日，全国放假1天。民众前往富寿省雄王庙祭祖，各地举行龙舟、摔跤、唱军鼓等民俗活动；家中与社区供桌摆放粽子、供品，门口悬挂国旗与节日横幅。',
    '越南站春季营销节点，传统服饰奥黛与供品周边需求集中；粽子、供盘等商品可与越南春节供应链复用。',
    [['越式粽子', 'banh chung vietnamese', 'P1'],
     ['越南奥黛', 'ao dai vietnam', 'P1'],
     ['供品盘摆件', 'hung kings offering plate', 'P2'],
     ['节日横幅', 'hung kings festival banner', 'P2'],
     ['雄王香案摆件', 'hung kings altar decor', 'P2'],
     ['祭祀香烛', 'incense sticks vietnam', 'P2'],
     ['传统斗笠', 'non la conical hat', 'P3'],
     ['木质供品托盘', 'wooden offering tray', 'P3'],
     ['节日灯笼', 'vietnamese festival lanterns', 'P3'],
     ['民俗舞蹈道具', 'traditional fan dance props', 'P3']]],

  ['五月五日节', 'Cinco de Mayo', '05-05', '05-05', 'LATAM',
    '5月5日，纪念1862年墨西哥普埃布拉战役，在美国已演变为墨西哥文化狂欢日。街道与餐厅悬挂剪纸彩旗，参加者戴宽边帽、披披风、摇沙锤，现场供应塔可、龙舌兰与玛格丽特；酒吧与社区举办派对、游行和皮纳塔活动。',
    '美国西语裔市场消费旺盛，宽边帽、沙锤与彩旗是派对刚需；4月中旬完成上架，充气仙人掌等大件适合户外场景。',
    [['墨西哥宽边帽', 'sombrero hat', 'P1'],
     ['墨西哥披风', 'mexican poncho', 'P1'],
     ['剪纸彩旗', 'papel picado banner', 'P1'],
     ['马拉卡斯沙锤', 'maracas', 'P1'],
     ['充气仙人掌', 'inflatable cactus', 'P2'],
     ['五月五日拉旗', 'cinco de mayo banner', 'P2'],
     ['墨西哥气球', 'fiesta balloons', 'P2'],
     ['派对餐盘餐具', 'fiesta plates napkins', 'P2'],
     ['塑料龙舌兰酒杯', 'shot glasses plastic party', 'P3'],
     ['墨西哥假胡子', 'fake mustache party', 'P3']]],

  ['母亲节（美国）', "Mother's Day", '05-10', '05-09', 'NA',
    '每年5月第二个星期日（2026年5月10日），美国最重要的送礼节日之一。家中与餐厅以康乃馨、鲜花礼盒布置，子女请母亲吃早午餐、赠送珠宝、鲜花与水疗礼品；当天教堂为母亲举行祝福仪式，商场鲜花与礼品专柜排起长队。',
    '女性礼品全年峰值，适合推高客单永生花与饰品；4月中旬完成上架，贺卡与礼盒包装直接影响转化，可提供定制服务溢价。',
    [['永生花礼盒', 'mothers day flower box', 'P1'],
     ['妈妈项链', 'mom necklace', 'P1'],
     ['水疗礼品篮', 'spa gift basket', 'P1'],
     ['定制保温杯', 'best mom tumbler', 'P1'],
     ['母亲节贺卡', 'mothers day card', 'P2'],
     ['母亲节拉旗', 'happy mothers day banner', 'P2'],
     ['妈妈围裙', 'mom apron kitchen', 'P2'],
     ['香薰蜡烛', 'mothers day scented candle', 'P2'],
     ['仿真玫瑰花束', 'mothers day roses artificial', 'P3'],
     ['定制妈妈相框', 'mom picture frame personalized', 'P3']]],

  ['阵亡将士纪念日', 'Memorial Day', '05-25', '05-31', 'NA',
    '美国联邦假日，5月最后一个星期一（2026年5月25日），纪念历次战争中阵亡的军人。当天家庭在墓地或纪念碑献花圈、插小旗、佩戴罂粟花胸针；同时长周末标志夏季开始，家庭在后院烧烤、去湖边度假，红白蓝装饰随处可见。',
    '爱国装饰与户外用品双需求，是夏季品类启动节点；墓碑小旗、花圈为节前刚需，户外烧烤用品可与暑期商品合并备货。',
    [['美国国旗', 'memorial day flags', 'P1'],
     ['爱国花环', 'patriotic wreath', 'P1'],
     ['墓碑小旗', 'grave flags cemetery', 'P1'],
     ['罂粟花胸针', 'poppy pin remembrance', 'P2'],
     ['红白蓝拉旗', 'patriotic banner', 'P2'],
     ['爱国气球', 'patriotic balloons', 'P2'],
     ['户外派对用品', 'patriotic party supplies', 'P2'],
     ['纪念餐桌中心饰', 'memorial table centerpiece', 'P3'],
     ['纪念蜡烛', 'memorial candles luminaries', 'P3'],
     ['退伍军人徽章', 'veterans button pins', 'P3']]],

  ['卫塞节', 'Vesak Day', '05-31', '05-20', 'SEA',
    '纪念佛陀诞生、成道与涅槃的节日（2026年5月31日，各国日期略有差异），东南亚佛教国家的公共假日。寺庙张挂佛教彩旗与莲花灯，举行浴佛、放生、布施与烛光绕行；家庭在佛龛供莲花、点蜡烛，民众穿白衣持戒行善。',
    '莲花灯、佛像与浴佛盆在泰国、马来西亚、新加坡有稳定需求；5月中旬完成上架，佛教用品注意包装庄重以提高评价。',
    [['莲花灯', 'lotus lantern', 'P1'],
     ['佛像摆件', 'buddha statue home', 'P1'],
     ['浴佛盆套装', 'vesak bathing buddha set', 'P1'],
     ['祈福蜡烛', 'vesak candles', 'P2'],
     ['佛教祈福彩旗', 'buddhist prayer flags', 'P2'],
     ['莲花供盘', 'vesak lotus tray', 'P2'],
     ['茉莉花串', 'jasmine garland fresh', 'P2'],
     ['佛香线香', 'buddhist incense sticks', 'P3'],
     ['布施钵', 'alms bowl buddhist', 'P3'],
     ['祈福纸灯笼', 'vesak paper lantern', 'P3']]],

  ['古尔邦节', 'Eid al-Adha / Hari Raya Haji', '05-27', '05-16', 'ME,SEA',
    '伊斯兰两大节日之一（2026年5月27日），纪念先知易卜拉欣献牲，放假约一周。首日清晨参加会礼，之后宰牲分赠亲友与穷人；节前家家户户购置新衣、打扫房屋、布置灯饰与餐桌，男性穿新长袍，节日期间走亲访友、互赠糖果点心。',
    '中东与马来市场节日男装为高客单品类，灯饰装饰可与开斋节共用供应链；4月下旬完成上架，糖果盘、礼品包装等配件走量。',
    [['男士阿拉伯长袍', 'thobe for men', 'P1'],
     ['节日灯饰', 'eid lights', 'P1'],
     ['节日糖果盘', 'eid serving tray', 'P1'],
     ['节日贺卡', 'eid mubarak card', 'P2'],
     ['礼品包装盒', 'eid gift wrapping', 'P2'],
     ['宰牲节主题装饰', 'eid al adha decorations', 'P2'],
     ['节日气球', 'eid balloons', 'P2'],
     ['男士礼拜帽', 'muslim skull cap men', 'P2'],
     ['节日餐具', 'eid tableware', 'P3'],
     ['清真寺墙饰挂件', 'eid wall art mosque', 'P3']]],

  ['父亲节', "Father's Day", '06-21', '06-20', 'NA',
    '美国父亲节为6月第三个星期日（2026年6月21日）。家中在后院举办烧烤派对，布置工具与运动主题装饰，子女赠送工具、户外用品与定制礼品；当天也是高尔夫、钓鱼、看棒球的热门日子，餐厅推出牛排与烧烤套餐。',
    '工具类、烧烤类是常青爆款，定制锤子、保温杯可做个性化溢价；5月下旬完成上架，礼品套装客单可做高。',
    [['多功能工具钳', 'multi tool for dad', 'P1'],
     ['烧烤工具套装', 'bbq grill set', 'P1'],
     ['爸爸保温杯', 'dad tumbler', 'P1'],
     ['定制锤子', 'personalized hammer dad', 'P2'],
     ['筋膜按摩枪', 'massage gun', 'P2'],
     ['父亲节贺卡', 'fathers day card', 'P2'],
     ['父亲节拉旗', 'happy fathers day banner', 'P2'],
     ['男士烧烤围裙', 'bbq apron dad', 'P2'],
     ['钓鱼礼品套装', 'fishing gifts dad', 'P3'],
     ['汽车清洁套装', 'car wash kit dad', 'P3']]],

  ['六月节（解放日）', 'Juneteenth', '06-19', '06-19', 'NA',
    '6月19日，纪念1865年美国黑奴获悉解放，2021年成为联邦假日。社区以红黑绿泛非色布置，举办游行、朗读、音乐节与家族团聚聚餐，街头售卖主题服饰、徽章与旗帜；节日近年认知度快速提升，商家参与度逐年增加。',
    '新兴节日，增速快竞争小，泛非色服饰与装饰适合提前布局；5月完成上架，1865主题与红黑绿配色是核心识别元素。',
    [['六月节旗帜', 'juneteenth flag', 'P1'],
     ['1865主题T恤', 'juneteenth shirt', 'P1'],
     ['红黑绿装饰', 'juneteenth decorations', 'P1'],
     ['自由日徽章', 'juneteenth pin', 'P2'],
     ['六月节拉旗', 'juneteenth banner', 'P2'],
     ['红黑绿气球', 'juneteenth balloons', 'P2'],
     ['1865主题水杯', 'juneteenth cup tumbler', 'P2'],
     ['六月节门挂', 'juneteenth door sign', 'P3'],
     ['自由主题项链', 'juneteenth necklace', 'P3'],
     ['纪念主题贴纸', 'juneteenth stickers', 'P3']]],

  ['巴西情人节', 'Dia dos Namorados', '06-12', '06-12', 'LATAM',
    '巴西情人节为6月12日（圣安东尼奥节前夜），情侣互赠礼物、共进浪漫晚餐。餐厅与公寓以红心形气球、玫瑰与蜡烛布置，商场出售巧克力、饰品与内衣礼盒；当天还举办相亲、集体婚礼登记等活动。',
    '避开2月情人节红海，针对巴西站单独备货；6月上旬为高峰，情侣饰品、巧克力与浪漫家居为主推品类。',
    [['情侣戒指', 'couple rings', 'P1'],
     ['爱心巧克力礼盒', 'chocolate gift box', 'P1'],
     ['浪漫晚餐蜡烛', 'romantic dinner candles', 'P1'],
     ['情侣对杯', 'couple mugs', 'P2'],
     ['爱心气球', 'heart balloons red', 'P2'],
     ['毛绒爱心抱枕', 'heart pillow plush', 'P2'],
     ['女士内衣礼盒', 'lingerie gift set', 'P2'],
     ['情侣相框', 'couple picture frame', 'P3'],
     ['浪漫桌布', 'romantic tablecloth red', 'P3'],
     ['仿真红玫瑰', 'red roses artificial', 'P3']]],

  ['伊斯兰新年', 'Islamic New Year (Hijri)', '06-17', '06-07', 'ME',
    '伊斯兰历正月初一（2026年约6月17日），穆斯林举行宗教祈祷、家庭聚会与年度回顾。部分地区清真寺举办讲座，家庭更换新日历，以绿色与新月元素轻量布置；节日氛围庄重安静，消费规模远小于两大尔德节。',
    '宗教贺卡、日历等轻量商品适合顺带布局，可与古尔邦节后的补货合并；不建议单独压大件库存。',
    [['伊斯兰日历', 'islamic calendar wall', 'P1'],
     ['新年贺卡', 'hijri new year card', 'P1'],
     ['清真糕点礼盒', 'halal sweets box', 'P2'],
     ['绿色主题气球', 'islamic new year balloons', 'P2'],
     ['清真寺摆件', 'mosque decor tabletop', 'P2'],
     ['新年拉旗', 'hijri new year banner', 'P2'],
     ['礼拜赞珠', 'tasbih prayer beads', 'P3'],
     ['绿色桌布', 'green tablecloth party', 'P3'],
     ['儿童新年手工', 'islamic new year crafts kids', 'P3'],
     ['新月挂件', 'crescent moon decoration', 'P3']]],

  ['加拿大日', 'Canada Day', '07-01', '07-01', 'NA',
    '7月1日加拿大国庆日，全国放假。渥太华举行升旗仪式与庆典，各地社区以红白枫叶主题装饰，举办游行、烧烤与烟花；民众穿红白服装、佩戴枫叶配饰参加街头派对，晚间聚集观看烟花。',
    '加拿大站7月主力节点，枫叶元素是与美国国庆的差异化卖点；6月中旬完成上架，红白派对套装走量稳定。',
    [['加拿大国旗', 'canada flag', 'P1'],
     ['枫叶主题装饰', 'canada day decorations', 'P1'],
     ['红白派对服装', 'canada day outfit', 'P1'],
     ['枫叶帽', 'canada maple leaf hat', 'P2'],
     ['红白气球', 'canada day balloons', 'P2'],
     ['加拿大日拉旗', 'canada day banner', 'P2'],
     ['派对餐具用品', 'canada day party supplies', 'P2'],
     ['枫叶纹身贴', 'maple leaf temporary tattoos', 'P3'],
     ['充气海狸道具', 'inflatable beaver canada', 'P3'],
     ['国庆纪念徽章', 'canada day pins', 'P3']]],

  ['美国独立日', 'Independence Day', '07-04', '07-04', 'NA',
    '7月4日美国国庆，全国放假。各地举行大游行，家庭在后院或湖畔举办烧烤派对，悬挂国旗、红白蓝气球与拉旗；白天有棒球赛与音乐节，晚间燃放烟花、挥舞安全烟花棒，商场与社区中心布置爱国主题场景。',
    '全年爱国主题消费峰值，6月初即进入流量高峰；国旗、派对用品走量巨大，遮阳篷、充气浮具等大件适合海外仓。',
    [['美国国旗', 'american flag 3x5', 'P1'],
     ['红白蓝主题装饰', '4th of july decorations', 'P1'],
     ['爱国主题服装', 'patriotic outfit', 'P1'],
     ['烧烤派对用品', '4th of july party supplies', 'P1'],
     ['户外遮阳篷', 'patriotic canopy tent', 'P2'],
     ['红白蓝气球', 'patriotic balloons', 'P2'],
     ['爱国拉旗', '4th of july banner', 'P2'],
     ['手持安全烟花棒', 'sparklers fireworks safe', 'P2'],
     ['红白蓝LED灯串', 'patriotic string lights', 'P3'],
     ['拍照道具套装', 'patriotic photo booth props', 'P3']]],

  ['新加坡国庆日', 'Singapore National Day', '08-09', '08-09', 'SEA',
    '8月9日新加坡独立纪念日，全国放假。滨海湾举行盛大庆典检阅礼与演出，全民领取国庆Funpack礼包，组屋区张挂红白国旗与星月旗；社区举行升旗仪式、聚餐与嘉年华，晚间集体观看烟花。',
    '新加坡站8月核心节点，红白配色与国庆周边走量；7月完成上架，助威道具与派对用品为节前刚需。',
    [['新加坡国旗', 'singapore flag', 'P1'],
     ['国庆徽章', 'singapore pin', 'P1'],
     ['国庆助威套装', 'ndp funpack kit', 'P2'],
     ['红白主题装饰', 'singapore red white decorations', 'P2'],
     ['国庆气球', 'singapore balloons', 'P2'],
     ['国庆拉旗', 'singapore national day banner', 'P2'],
     ['星月主题贴纸', 'singapore stars moon stickers', 'P2'],
     ['派对餐具用品', 'singapore party supplies', 'P3'],
     ['充气拍手器', 'inflatable clappers noisemakers', 'P3'],
     ['红色国庆T恤', 'ndp shirt red', 'P3']]],

  ['印尼独立日', 'Indonesian Independence Day', '08-17', '08-17', 'SEA',
    '8月17日印尼独立纪念日，全国放假。家家户户悬挂红白双色旗，社区举行爬油杆、布袋赛跑、吃虾片等民俗比赛，红色头巾与服饰热销；当天举行升国旗仪式，街区搭起比赛帐篷与聚餐。',
    '国旗与民俗比赛道具需求集中，7月下旬进入高峰；红白配色头巾可同时覆盖日常穿戴与节日场景。',
    [['红白双色旗', 'bendera merah putih', 'P1'],
     ['爬杆游戏道具', 'panjat pinang set', 'P1'],
     ['红白配色头巾', 'merah putih hijab', 'P1'],
     ['社区比赛道具', 'lomba 17 agustus games', 'P2'],
     ['红白气球', 'merah putih balloons', 'P2'],
     ['国庆拉旗', 'hut ri banner', 'P2'],
     ['布袋赛跑袋', 'sack race bags kids', 'P2'],
     ['吃虾片比赛道具', 'lomba makan kerupuk kit', 'P3'],
     ['红白手环', 'merah putih wristband', 'P3'],
     ['社区装饰长旗', 'umbul umbul banners', 'P3']]],

  ['马来西亚国庆日', 'Malaysia National Day', '08-31', '08-31', 'SEA',
    '8月31日马来亚联合邦独立纪念日，全国放假。吉隆坡举行盛大游行与庆典，全城悬挂辉煌条纹国旗；民众穿峇迪衫、佩戴国旗手环，商场以国旗色布置，举办展销与嘉年华，晚间观看烟花。',
    '国旗、峇迪衫与国庆周边在8月底走量；8月上旬完成上架，国旗配饰可多件装出售。',
    [['马来西亚国旗', 'malaysian flag', 'P1'],
     ['峇迪衫', 'batik shirt malaysia', 'P1'],
     ['国旗手腕带', 'malaysia wristband', 'P2'],
     ['国庆装饰条幅', 'jalur gemilang decorations', 'P2'],
     ['国庆气球', 'malaysia day balloons', 'P2'],
     ['国庆拉旗', 'malaysia national day banner', 'P2'],
     ['双峰塔主题装饰', 'klcc decor party', 'P2'],
     ['派对餐具用品', 'malaysia party supplies', 'P3'],
     ['助威喇叭', 'malaysia vuvuzela horn', 'P3'],
     ['国旗纹身贴', 'malaysia flag temporary tattoo', 'P3']]],

  ['先知诞辰', 'Mawlid al-Nabi', '08-25', '08-14', 'ME',
    '伊斯兰历三月十二日（2026年约8月25日），纪念先知穆罕默德诞辰。清真寺张挂绿色灯饰与横幅，举行诵经与赞圣活动，向儿童发放甜点；家庭以绿色灯笼、贺卡做轻量装饰，准备清真糕点分享。',
    '宗教氛围浓，绿色灯饰与贺卡有稳定小需求；8月中旬完成上架，适合与日常礼拜用品关联销售。',
    [['先知诞辰灯饰', 'mawlid lights', 'P1'],
     ['宗教主题贺卡', 'mawlid card', 'P1'],
     ['绿色主题横幅', 'mawlid banner', 'P2'],
     ['清真甜点礼盒', 'halal sweets box', 'P2'],
     ['绿色气球', 'mawlid balloons', 'P2'],
     ['清真寺造型灯笼', 'mawlid lantern mosque', 'P2'],
     ['礼拜赞珠', 'tasbih prayer beads', 'P3'],
     ['绿色桌旗', 'mawlid table runner', 'P3'],
     ['儿童宗教绘本', 'prophet muhammad book kids', 'P3'],
     ['香薰沉香棒', 'bakhoor incense', 'P3']]],

  ['菲律宾圣诞季启动', 'Philippines Christmas "BER Months"', '09-01', '09-01', 'SEA',
    '菲律宾有全球最长圣诞季，从9月第一个星期（BER月份开始）即启动。家庭在门窗悬挂星灯Parol，播放圣诞歌曲，商场布置圣诞树与圣诞场景；9月起周末陆续有圣诞派对，装饰销售一直持续到12月。',
    '东南亚最早的圣诞备货窗口，星灯Parol是菲律宾特色爆款；8月完成上架抢占首发流量，圣诞装饰销售周期长达4个月。',
    [['圣诞星灯', 'parol christmas lantern', 'P1'],
     ['仿真圣诞树', 'christmas tree artificial', 'P1'],
     ['圣诞花环', 'christmas wreath', 'P2'],
     ['家庭圣诞衫', 'christmas family shirts', 'P2'],
     ['圣诞灯串', 'christmas lights string', 'P2'],
     ['圣诞拉旗', 'christmas banner merry', 'P2'],
     ['星灯手工材料包', 'parol craft kit kids', 'P2'],
     ['圣诞袜', 'christmas stockings set', 'P3'],
     ['圣诞桌旗', 'christmas table runner', 'P3'],
     ['蓝牙音箱礼物', 'bluetooth speaker gift', 'P3']]],

  ['巴西独立日', 'Brazil Independence Day', '09-07', '09-07', 'LATAM',
    '9月7日巴西独立纪念日，全国放假。巴西利亚与里约举行阅兵与飞行表演，街头张挂黄绿国旗与串旗；民众穿黄绿主题T恤、挥舞喇叭参加游行，商场以国旗色布置促销。',
    '巴西站9月爱国主题节点，9月初为高峰；国旗与黄绿服饰走量，足球元素可关联销售。',
    [['巴西国旗', 'brazil flag', 'P1'],
     ['黄绿主题T恤', 'brazil green yellow shirt', 'P1'],
     ['彩色串旗', 'bunting banner outdoor', 'P2'],
     ['助威喇叭', 'brazil vuvuzela', 'P2'],
     ['黄绿气球', 'brazil balloons', 'P2'],
     ['独立日拉旗', 'independencia do brasil banner', 'P2'],
     ['派对餐具用品', 'brazil party supplies', 'P2'],
     ['黄绿手环', 'brazil wristband', 'P3'],
     ['国旗脸贴', 'brazil flag face stickers', 'P3'],
     ['充气足球', 'inflatable soccer ball beach', 'P3']]],

  ['劳工节', 'Labor Day', '09-07', '09-06', 'NA',
    '美国与加拿大9月第一个星期一（2026年9月7日），长周末标志夏季结束。家庭举办最后一波烧烤野餐与泳池派对，商场借假期举行大促；街道与公园可见白色主题派对、户外游戏与跳蚤市场。',
    '户外与烧烤用品夏季最后一波出清，零售平台普遍有大促可蹭流量；8月中下旬为高峰，注意控制库存避免节后积压。',
    [['野餐防潮垫', 'picnic blanket waterproof', 'P1'],
     ['充气戏水浮具', 'pool float inflatable', 'P1'],
     ['烧烤工具套装', 'labor day bbq set', 'P1'],
     ['白色派对服装', 'white party outfit women', 'P2'],
     ['冷藏保温包', 'cooler bag insulated', 'P2'],
     ['一次性派对餐具', 'labor day party supplies', 'P2'],
     ['劳工节拉旗', 'labor day banner', 'P2'],
     ['户外游戏套装', 'yard games outdoor set', 'P3'],
     ['户外灯串', 'outdoor string lights', 'P3'],
     ['派对冷饮杯', 'plastic cups party bulk', 'P3']]],

  ['墨西哥独立日', 'Mexican Independence Day', '09-16', '09-16', 'LATAM',
    '9月16日多洛雷斯呼声纪念日，墨西哥最重要的国庆节日。9月15日深夜总统在国家宫敲响多洛雷斯钟、高呼爱国口号，全城挥舞绿白红国旗与响铃；16日举行阅兵，街头有骑术表演、墨西哥美食与马里亚奇音乐。',
    '墨西哥站9月最大节点，国旗、宽边帽与绿白红装饰需求集中；9月上旬完成上架，响铃与沙锤是声音类刚需。',
    [['墨西哥国旗', 'mexico flag', 'P1'],
     ['墨西哥宽边帽', 'mexican charro hat', 'P1'],
     ['绿白红装饰', 'mexico independence decorations', 'P1'],
     ['庆典沙锤', 'mexican maracas', 'P2'],
     ['绿白红气球', 'mexico balloons', 'P2'],
     ['爱国拉旗', 'viva mexico banner', 'P2'],
     ['派对餐具用品', 'mexico party supplies', 'P2'],
     ['多洛雷斯钟挂饰', 'campana de dolores decor', 'P3'],
     ['墨西哥披风', 'poncho mexican adult', 'P3'],
     ['充气辣椒道具', 'inflatable chili pepper', 'P3']]],

  ['智利国庆日', 'Fiestas Patrias (Chile)', '09-18', '09-18', 'LATAM',
    '9月18–19日智利国庆长周末。家庭在fondas帐篷集市跳昆卡舞、吃烤肉、喝红酒，空中满是风筝；人们佩戴瓦索牛仔帽、披毛呢披风，红白蓝三色装饰遍布街头与庭院。',
    '智利市场小而精，牛仔帽、风筝等民俗商品竞争小；9月上旬完成上架，烧烤工具可与北美暑期供应链复用。',
    [['智利国旗', 'chile flag', 'P1'],
     ['瓦索牛仔帽', 'chilean huaso hat', 'P1'],
     ['国庆风筝', 'cometas chile kite', 'P2'],
     ['庆典装饰', 'fiestas patrias decorations', 'P2'],
     ['智利气球', 'chile balloons', 'P2'],
     ['国庆拉旗', 'fiestas patrias banner', 'P2'],
     ['毛呢披风', 'chilean poncho wool', 'P2'],
     ['派对餐具用品', 'chile party supplies', 'P3'],
     ['昆卡舞手帕', 'chilean cueca handkerchief', 'P3'],
     ['烤肉烧烤工具', 'chilean asado grill set', 'P3']]],

  ['慕尼黑啤酒节', 'Oktoberfest', '09-19', '09-18', 'EU',
    '9月中下旬（2026年9月19日起）德国慕尼黑世界最大民俗节日，持续约两周。特蕾莎草坪搭起巨型啤酒帐篷，女性穿紧身裙Dirndl、男性穿皮裤Lederhosen，手持1升啤酒杯，现场有铜管乐队、旋转木马与椒盐卷饼、姜饼等集市食品。',
    '主题装扮客单高，啤酒杯与蓝白格装饰全年可售、节前爆发；8月完成上架，套装（帽+杯+装饰）利润最高。',
    [['陶瓷啤酒杯', 'oktoberfest beer stein', 'P1'],
     ['女士紧身裙装', 'dirndl dress women', 'P1'],
     ['男士皮裤装', 'lederhosen men', 'P1'],
     ['椒盐卷饼装饰', 'pretzel decorations', 'P2'],
     ['蓝白格装饰', 'oktoberfest decorations', 'P2'],
     ['巴伐利亚羽毛帽', 'bavarian hat feather', 'P2'],
     ['啤酒节拉旗', 'oktoberfest banner', 'P2'],
     ['蓝白格桌布', 'bavarian tablecloth', 'P3'],
     ['1升塑料啤酒杯', 'oktoberfest plastic beer mug', 'P3'],
     ['姜饼心挂饰', 'gingerbread heart ornament', 'P3']]],

  ['沙特国庆日', 'Saudi National Day', '09-23', '09-23', 'ME',
    '9月23日沙特阿拉伯国庆日，全国放假。利雅得举行烟花、飞行表演与娱乐活动，街道与商场以绿色国旗主题布置；民众穿绿色T恤、佩戴徽章与围巾，车灯与建筑亮起绿色灯光，节日消费氛围随愿景2030改革逐年升温。',
    '海湾新兴电商节点，绿色服饰与配饰增速快；9月上旬完成上架，绿色围巾、车贴适合走量。',
    [['沙特国旗', 'saudi flag', 'P1'],
     ['国庆主题T恤', 'saudi national day shirt', 'P1'],
     ['国庆徽章', 'saudi pin', 'P2'],
     ['绿色气球套装', 'saudi green balloons', 'P2'],
     ['绿色拉旗', 'saudi national day banner', 'P2'],
     ['国庆围巾', 'saudi scarf green', 'P2'],
     ['绿色主题装饰', 'saudi decorations green', 'P2'],
     ['绿色车贴', 'saudi car stickers', 'P3'],
     ['国庆手环', 'saudi wristband green', 'P3'],
     ['愿景2030主题礼品', 'vision 2030 gifts', 'P3']]],

  ['中秋节', 'Mid-Autumn Festival', '09-25', '09-15', 'SEA',
    '农历八月十五（2026年9月25日），东南亚华人普遍庆祝。节前晚辈送月饼礼盒，家中摆茶具赏月；当晚儿童手提兔子灯笼、花灯游园，街道与商场布置灯笼场景与秋季装饰，部分地区举办灯会与舞龙。',
    '月饼模具与灯笼为特色品类，节前两周流量集中；茶具、玉兔摆件等中式礼品适合组合销售，注意食品进口限制，主推模具与包装。',
    [['月饼模具', 'mooncake mold press', 'P1'],
     ['兔子灯笼', 'rabbit lantern kids', 'P1'],
     ['月饼礼盒包装', 'mooncake gift box packaging', 'P1'],
     ['中秋花灯', 'mid autumn lantern', 'P2'],
     ['功夫茶具', 'chinese tea set', 'P2'],
     ['中秋拉旗', 'mid autumn festival banner', 'P2'],
     ['中式茶盘', 'chinese tea tray wood', 'P2'],
     ['玉兔摆件', 'jade rabbit figurine', 'P3'],
     ['儿童灯笼手工包', 'lantern craft kit kids', 'P3'],
     ['桂花茶饮', 'osmanthus tea chinese', 'P3']]],

  ['加拿大感恩节', 'Canadian Thanksgiving', '10-12', '10-11', 'NA',
    '加拿大感恩节为10月第二个星期一（2026年10月12日）。家庭以枫叶花环、南瓜与松果布置餐桌，享用火鸡或火腿丰收大餐；长周末恰逢赏枫高峰，人们前往郊野观赏红叶，商场布置秋季丰收场景。',
    '南瓜、枫叶等秋季装饰比美国感恩节提前走量；9月下旬完成上架，丰收角、麦穗等摆件可与万圣节商品同期陈列。',
    [['枫叶花环', 'fall maple leaf wreath', 'P1'],
     ['南瓜装饰摆件', 'pumpkin decorations set', 'P1'],
     ['火鸡主题装饰', 'thanksgiving turkey decor', 'P2'],
     ['丰收角摆件', 'cornucopia basket', 'P2'],
     ['感恩拉旗', 'give thanks banner', 'P2'],
     ['枫叶灯串', 'fall maple leaf string lights', 'P2'],
     ['松果装饰摆件', 'pinecone decorations', 'P2'],
     ['丰收餐桌桌旗', 'thanksgiving table runner', 'P3'],
     ['秋季门挂', 'fall door sign harvest', 'P3'],
     ['干小麦穗束', 'dried wheat bundle decor', 'P3']]],

  ['万圣节', 'Halloween', '10-31', '10-31', 'NA,EU,LATAM',
    '10月31日西方年度最具商业价值的装扮节日。10月起家庭在门前布置南瓜灯、墓碑、蜘蛛网与电动恐怖道具；31日傍晚儿童化妆穿服装、挎讨糖袋逐户讨糖，成年人参加变装派对与鬼屋活动，宠物也多有主题装扮。',
    '全年最大装扮类消费节点，9月起进入高峰；服装、户外装饰、宠物服全品类开花，南瓜雕刻工具与假血化妆品适合做配件组合。',
    [['万圣节服装', 'halloween costume adult', 'P1'],
     ['南瓜灯（雕刻桶）', 'jack o lantern bucket', 'P1'],
     ['户外恐怖装饰', 'halloween decorations outdoor', 'P1'],
     ['讨糖袋', 'trick or treat bag', 'P1'],
     ['电动恐怖道具', 'animatronics halloween', 'P2'],
     ['宠物万圣节服装', 'dog halloween costume', 'P2'],
     ['万圣节拉旗', 'happy halloween banner', 'P2'],
     ['南瓜雕刻工具', 'pumpkin carving kit', 'P2'],
     ['万圣节灯串', 'halloween string lights', 'P3'],
     ['假血化妆套装', 'fake blood makeup kit', 'P3']]],

  ['亡灵节', 'Día de los Muertos', '11-02', '11-02', 'LATAM',
    '11月1–2日墨西哥祭祖节日（1日为幼灵、2日为成灵），2008年入选非遗。家中搭设祭坛，铺万寿菊花瓣引路，摆放糖骷髅、逝者照片、蜡烛与生前喜爱的食物；街道张挂剪纸彩旗，女性扮卡特里娜、画糖骷髅妆容，墓地有通宵音乐守灵。',
    '与万圣节明确区分：亡灵节色彩艳丽（橙紫为主）、家庭与宗教属性强；万寿菊、糖骷髅与卡特里娜是专属品类，溢价高竞争小。',
    [['糖骷髅装饰', 'sugar skull decorations', 'P1'],
     ['万寿菊花环', 'marigold garland', 'P1'],
     ['卡特里娜装扮', 'catrina costume women', 'P1'],
     ['祭坛蜡烛', 'day of the dead candles', 'P1'],
     ['亡灵节脸贴', 'day of the dead face stickers', 'P2'],
     ['祭坛剪纸彩旗', 'papel picado day of the dead', 'P2'],
     ['亡灵节拉旗', 'day of the dead banner', 'P2'],
     ['骷髅派对餐具', 'day of the dead tableware', 'P2'],
     ['卡特里娜花朵头箍', 'catrina flower headband', 'P3'],
     ['糖骷髅模具', 'sugar skull mold clay', 'P3']]],

  ['盖伊·福克斯之夜', 'Guy Fawkes Night', '11-05', '11-05', 'EU',
    '11月5日英国传统篝火焰火之夜，纪念1605年火药阴谋事件。傍晚社区点燃巨大篝火、燃放烟花，儿童佩戴面具、挥舞安全火花棒；人们在篝火旁烤香肠与棉花糖，因面具随影视作品符号化，节日有全球长尾关注度。',
    '英国站11月特色节点，面具全球有长尾需求可常年在售；10月下旬完成上架，火花棒、篝火派对装饰为节前刚需。',
    [['福克斯面具', 'guy fawkes mask', 'P1'],
     ['烟花用品', 'british fireworks display', 'P1'],
     ['篝火派对装饰', 'bonfire night decorations', 'P2'],
     ['英国国旗', 'union jack flag', 'P2'],
     ['篝火主题拉旗', 'bonfire night banner', 'P2'],
     ['手持安全火花棒', 'sparklers hand held safe', 'P2'],
     ['户外保暖毛毯', 'outdoor blanket waterproof', 'P3'],
     ['篝火主题马克杯', 'bonfire night mug', 'P3'],
     ['烤棉花糖棒', 'marshmallow roasting sticks', 'P3'],
     ['纪念徽章贴纸', 'remember the fifth pin', 'P3']]],

  ['排灯节', 'Diwali', '11-08', '10-29', 'ME,SEA',
    '印度教灯节（2026年11月8日），持续5天。节前大扫除、绘制蓝果丽地画，当晚家家户户点亮陶土油灯与彩灯，门窗悬挂印度灯笼；5天内穿新衣、拜吉祥天女与象神、燃放烟花、互赠甜食礼盒，海湾印度裔社区同样隆重庆祝。',
    '油灯、彩灯与蓝果丽用品为爆款，10月下旬进入高峰；面向海湾与新加坡南亚裔社区，神像与甜食注意宗教敏感性，主推装饰与灯饰。',
    [['陶土油灯', 'diwali diyas clay', 'P1'],
     ['蓝果丽模板', 'rangoli stencil', 'P1'],
     ['排灯节彩灯', 'diwali lights string', 'P1'],
     ['印度灯笼', 'akash kandil lantern', 'P1'],
     ['吉祥神像', 'lakshmi ganesh idol', 'P2'],
     ['排灯节拉旗', 'happy diwali banner', 'P2'],
     ['蓝果丽彩粉', 'rangoli colors powder', 'P2'],
     ['印度甜食礼盒', 'diwali sweets gift box', 'P2'],
     ['节日蜡烛', 'diwali candles tea light', 'P3'],
     ['莲花烛台摆件', 'lotus tea light holder', 'P3']]],

  ['退伍军人节/荣军纪念日', 'Veterans Day / Remembrance Day', '11-11', '11-11', 'NA,EU',
    '11月11日美国退伍军人节与英联邦荣军纪念日。当天11时举行两分钟默哀，民众佩戴红色罂粟花胸针，教堂与纪念碑献花圈；商场、学校与政界人士出席纪念仪式，悬挂国旗，向退伍军人致谢。',
    '罂粟胸针是标志性消耗品，10月起即有稳定采购；爱国主题装饰可与阵亡将士纪念日共用供应链。',
    [['罂粟花胸针', 'remembrance poppy brooch', 'P1'],
     ['纪念花圈', 'remembrance wreath', 'P1'],
     ['退伍军人纪念帽', 'veterans cap', 'P2'],
     ['美国国旗', 'american flag 3x5', 'P2'],
     ['纪念餐桌中心饰', 'veterans table centerpiece', 'P2'],
     ['感谢拉旗', 'thank you veterans banner', 'P2'],
     ['红白蓝气球', 'patriotic balloons', 'P2'],
     ['感谢卡片', 'veterans thank you cards', 'P3'],
     ['军人主题摆件', 'military figurine', 'P3'],
     ['黄丝带装饰', 'yellow ribbon decoration', 'P3']]],

  ['双十一购物节', "Singles' Day / 11.11 Sale", '11-11', '11-11', 'NA,EU,SEA,LATAM',
    '11月11日起源于中国的全球电商购物节。速卖通、Temu等跨境平台提前数周预热，发放优惠券并直播带货；当天24小时限时折扣，买家重点抢购美妆、3C、服饰与家居，包裹量为全年峰值之一。',
    '卖家全年冲量节点，提前一个月提报平台活动；美妆套装、3C配件折扣引流效果最好，准备充足库存与促销物料。',
    [['美妆礼盒套装', 'makeup gift set', 'P1'],
     ['电子盲盒福袋', 'mystery box electronics', 'P1'],
     ['手机配件套装', 'phone accessories bundle', 'P1'],
     ['情侣手机壳', 'couple phone case', 'P2'],
     ['双十一促销吊旗', '11.11 sale banner', 'P2'],
     ['折扣贴纸', 'discount stickers retail', 'P2'],
     ['礼品包装手提袋', 'gift bags with handles', 'P2'],
     ['快充数据线', 'fast charging cable usb', 'P3'],
     ['家居福袋', 'home goods mystery box', 'P3'],
     ['数字11气球', 'number 11 balloons', 'P3']]],

  ['墨西哥 Buen Fin 购物节', 'El Buen Fin', '11-13', '11-19', 'LATAM',
    '墨西哥年度最大购物节，11月中旬长周末（2026年11月13日起），由政府与商界联合推动。家电、家具与百货折扣力度全年最大，商场延长营业时间、布置促销吊旗，民众以分期方式集中采购大件，被称为墨西哥版黑五。',
    '墨西哥站黑五同级节点，家电与礼品类卖家重点参与；11月初完成促销物料与库存，价格标签与分期信息要清晰。',
    [['小型家电', 'small appliances deals', 'P1'],
     ['促销吊旗', 'el buen fin sale banner', 'P1'],
     ['礼品卡套', 'gift card holder', 'P2'],
     ['折扣贴纸', 'discount stickers price', 'P2'],
     ['促销海报', 'el buen fin poster', 'P2'],
     ['购物节气球', 'el buen fin balloons', 'P3'],
     ['环保购物袋', 'reusable shopping bags foldable', 'P3'],
     ['店铺价格标签', 'price tags labels blank', 'P3'],
     ['促销展台桌布', 'el buen fin tablecloth', 'P3'],
     ['西语促销横幅', 'ofertas banner spanish', 'P3']]],

  ['水灯节', 'Loy Krathong', '11-24', '11-13', 'SEA',
    '泰历十二月满月夜（2026年11月24日）。人们用蕉叶底座制作水灯，插上蜡烛、香与鲜花，放入河中祈福；清迈同时举办万人天灯活动，天空飘满天灯，街道有花车游行、选美与传统舞蹈表演，是泰国旅游热度最高的节日之一。',
    '水灯底座、蜡烛与天灯为刚需，11月中旬为高峰；面向游客主推天灯与水灯DIY材料，注意各地禁放政策对需求节奏的影响。',
    [['水灯底座', 'krathong floating basket', 'P1'],
     ['天灯', 'sky lanterns release', 'P1'],
     ['水灯蜡烛', 'krathong candles', 'P1'],
     ['泰国传统服饰', 'thai traditional dress women', 'P2'],
     ['水灯手工材料包', 'krathong craft kit', 'P2'],
     ['水灯线香', 'krathong incense sticks', 'P2'],
     ['拜水灯供盘', 'loy krathong offering tray', 'P2'],
     ['水灯节拉旗', 'loy krathong banner', 'P3'],
     ['泰式舞蹈头饰', 'thai dance headdress gold', 'P3'],
     ['防水荧光棒', 'waterproof glow sticks', 'P3']]],

  ['感恩节', 'Thanksgiving', '11-26', '11-25', 'NA',
    '美国最重要的家庭团圆节日，11月第四个星期四（2026年11月26日）。儿女返乡，上午观看梅西感恩节大游行，下午全家烤火鸡、布置南瓜与秋季藤条餐桌；晚间观看橄榄球赛，商场黑五预热从当日深夜开始。',
    '火鸡厨具与秋季装饰常青；备货窗口紧接黑五，两节点合并备货，火鸡烤盘、餐桌装饰在11月初进入高峰。',
    [['火鸡烤盘', 'turkey roasting pan', 'P1'],
     ['秋季藤条装饰', 'fall garland maple', 'P1'],
     ['南瓜主题装饰', 'thanksgiving decorations', 'P1'],
     ['火鸡造型帽', 'turkey hat', 'P2'],
     ['餐桌装饰套装', 'thanksgiving table decor', 'P2'],
     ['感恩拉旗', 'give thanks banner', 'P2'],
     ['火鸡调料注射器', 'turkey baster injector', 'P2'],
     ['火鸡主题纸盘', 'thanksgiving plates napkins', 'P3'],
     ['秋季灯串', 'fall string lights maple', 'P3'],
     ['橄榄球赛派对用品', 'football party supplies', 'P3']]],

  ['黑色星期五', 'Black Friday', '11-27', '11-26', 'NA,EU,LATAM',
    '感恩节后首日（2026年11月27日），全球折扣力度峰值。线下商场凌晨开门，顾客带折叠椅彻夜排队；线上同步推出限时秒杀，电子、家电、服饰为搜索热点，店铺张贴黑五海报与折扣标签。',
    '全年最大出单日，海运大件须按45天提前期倒推；促销海报、价签等物料与商品同步准备，黑五周末承接至网一。',
    [['电子配件', 'electronics accessories', 'P1'],
     ['促销海报物料', 'black friday poster', 'P1'],
     ['节日购物袋', 'shopping bags retail', 'P2'],
     ['排队折叠椅', 'folding chair portable', 'P2'],
     ['黑红气球', 'black friday balloons', 'P2'],
     ['黑五挂旗', 'black friday banner', 'P2'],
     ['折扣价签贴纸', 'black friday stickers', 'P3'],
     ['促销桌布', 'black friday tablecloth', 'P3'],
     ['排队保暖毯', 'outdoor blanket fleece', 'P3'],
     ['黑五主题保温杯', 'black friday tumbler cup', 'P3']]],

  ['网络星期一', 'Cyber Monday', '11-30', '11-29', 'NA,EU',
    '感恩节后的星期一（2026年11月30日），线上专属购物节。上班族在节后第一天集中网购，3C数码、软件订阅、游戏外设与办公用品折扣集中，电商以免运费、限时秒杀延续黑五流量。',
    '黑五承接节点，数码与游戏外设是主战场；11月上旬完成备货，键鼠、耳机等高周转品类可与黑五共用库存。',
    [['笔记本电脑配件', 'laptop accessories bundle', 'P1'],
     ['无线耳机', 'wireless earbuds', 'P1'],
     ['游戏外设', 'gaming accessories', 'P1'],
     ['手机支架', 'phone stand adjustable', 'P2'],
     ['键盘鼠标套装', 'keyboard mouse combo', 'P2'],
     ['直播补光灯', 'ring light with stand', 'P2'],
     ['USB扩展坞', 'usb hub docking station', 'P2'],
     ['高清网络摄像头', 'webcam 1080p', 'P3'],
     ['大号电竞桌垫', 'mouse pad large gaming', 'P3'],
     ['数码收纳包', 'cable organizer bag travel', 'P3']]],

  ['阿联酋国庆日', 'UAE National Day', '12-02', '12-02', 'ME',
    '12月2日阿联酋建国纪念日，全国放假。阿布扎比与迪拜举行阅兵、烟花与飞行表演，商场与街道以国旗四色（绿白黑红）布置；民众佩戴围巾、徽章，车身贴国旗色车贴，家庭在沙漠与海滩搭帐篷聚餐。',
    '海湾高购买力节点，围巾、车贴等国旗色商品走量；11月中旬完成上架，四色手环、脸绘等派对用品适合家庭采购。',
    [['阿联酋国旗', 'uae flag', 'P1'],
     ['国旗色围巾', 'uae flag scarf', 'P1'],
     ['国庆徽章', 'uae pin', 'P2'],
     ['国庆车贴', 'uae car stickers', 'P2'],
     ['四色气球', 'uae balloons', 'P2'],
     ['国庆拉旗', 'uae national day banner', 'P2'],
     ['四色手环', 'uae wristband colors', 'P2'],
     ['国庆主题T恤', 'uae national day shirt', 'P3'],
     ['四色脸部彩绘', 'uae face paint kit', 'P3'],
     ['国庆礼品袋', 'uae gift bags', 'P3']]],

  ['圣尼古拉斯节', 'Sinterklaas / St. Nicholas Day', '12-06', '12-06', 'EU',
    '12月5日圣尼古拉斯夜（荷兰12月6日庆祝），荷兰、比利时、德国等地儿童最重要的送礼节日。圣尼古拉斯戴主教帽、持权杖，助手把礼物装入礼物袋；儿童把靴子放在壁炉旁，6日拆字母巧克力、香料饼干与惊喜小礼物，全家玩“惊喜诗”游戏。',
    '欧洲12月礼品季开端，针对低地国家差异化选品；主教帽、字母巧克力模具与饼干模具为特色品类，11月中旬完成上架。',
    [['圣尼古拉斯主教帽', 'sinterklaas mijter hat', 'P1'],
     ['字母巧克力模具', 'chocolate letter mold', 'P1'],
     ['香料饼干模具', 'speculaas mold', 'P2'],
     ['惊喜礼品包装', 'sinterklaas surprises wrapping', 'P2'],
     ['圣尼古拉斯权杖', 'sinterklaas staff props', 'P2'],
     ['圣尼古拉斯礼物袋', 'zak van sinterklaas bag', 'P2'],
     ['靴子装饰套装', 'schoen zetten decor kids', 'P2'],
     ['香料小圆饼糖', 'pepernoten candy mold', 'P3'],
     ['圣尼古拉斯披风', 'sinterklaas cape red', 'P3'],
     ['窗贴装饰', 'sinterklaas raamdecoratie stickers', 'P3']]],

  ['拉斯波萨达斯', 'Las Posadas', '12-16', '12-16', 'LATAM',
    '墨西哥12月16–24日连续九晚的圣诞巡游，重现圣母玛利亚寻找客栈。邻里组队持蜡烛游行、唱祈祷歌，每晚派对以皮纳塔为中心，儿童挥棒打破皮纳塔抢糖果；门口摆放纸袋烛灯照路，供应波佐莱汤与圣诞热饮。',
    '墨西哥圣诞季特色节点，皮纳塔为派对刚需；12月上旬进入高峰，皮纳塔棒子、糖果填充与烛灯可做组合。',
    [['皮纳塔', 'pinata mexican pull string', 'P1'],
     ['纸袋烛灯', 'luminarias bags candles', 'P1'],
     ['波佐莱汤锅', 'pozole pot large', 'P2'],
     ['巡游天使蜡烛', 'posada candles set', 'P2'],
     ['圣诞拉美拉旗', 'las posadas banner', 'P2'],
     ['皮纳塔击打棒', 'pinata stick wooden', 'P2'],
     ['皮纳塔填充糖果玩具', 'pinata filler toys candy', 'P3'],
     ['儿童圣诞巡游服', 'nativity costume kids', 'P3'],
     ['天使光环发箍', 'angel halo headband', 'P3'],
     ['圣诞热饮锅', 'ponche navideno pot', 'P3']]],

  ['圣诞节', 'Christmas', '12-25', '12-25', 'NA,EU,SEA,LATAM',
    '12月25日全球最重要的宗教与商业节日。12月起家中搭圣诞树、挂装饰球与灯饰，门悬花环、壁炉挂圣诞袜；24日平安夜教堂礼拜、家庭交换礼物，25日圣诞大餐，儿童从降临节日历开始倒数整个12月。',
    '全年最大备货季，海运大件须按45天提前期；10月起进入高峰，圣诞树、装饰红海拼设计与套装，降临日历需最早上架。',
    [['仿真圣诞树', 'artificial christmas tree', 'P1'],
     ['装饰球挂件', 'christmas ornaments set', 'P1'],
     ['圣诞毛衣', 'ugly christmas sweater', 'P1'],
     ['降临节日历', 'advent calendar filled', 'P1'],
     ['圣诞灯饰', 'christmas lights string', 'P1'],
     ['圣诞袜', 'christmas stockings set', 'P2'],
     ['圣诞花环', 'christmas wreath front door', 'P2'],
     ['圣诞拉旗', 'merry christmas banner', 'P2'],
     ['礼品包装纸', 'christmas wrapping paper roll', 'P2'],
     ['圣诞树顶星', 'tree topper star lighted', 'P3']]],

  ['节礼日', 'Boxing Day', '12-26', '12-26', 'NA,EU',
    '12月26日英联邦国家公共假日。全年力度最大的清仓促销日之一，商场凌晨开门排起长队，圣诞商品大幅折扣；家庭在圣诞后第一天休息、观看体育赛事，并开始收纳圣诞树与装饰。',
    '圣诞库存清仓节点，促销物料与节日收纳商品（收纳箱、树袋、装饰收纳盒）借势走量；12月中旬备好收纳品类库存。',
    [['节礼日促销牌', 'boxing day sale sign', 'P1'],
     ['节日收纳箱', 'christmas storage boxes', 'P2'],
     ['圣诞树收纳袋', 'christmas tree storage bag', 'P2'],
     ['装饰球收纳盒', 'ornament storage box', 'P2'],
     ['灯串收纳盘', 'christmas light storage reel', 'P2'],
     ['清仓促销横幅', 'boxing day sale banner', 'P3'],
     ['清仓气球', 'boxing day balloons', 'P3'],
     ['折扣贴纸', 'boxing day discount stickers', 'P3'],
     ['礼品盒清仓', 'gift boxes with lids bulk', 'P3'],
     ['礼品包装纸清仓', 'christmas wrapping paper bulk', 'P3']]],

  // ============ V1.2 新增全球节日 ============
  ['登霄夜', 'Isra and Mi’raj', '01-15', '01-04', 'ME',
    '伊斯兰历7月27日夜，纪念先知穆罕默德乘天马夜行耶路撒冷、登霄受礼。节前穆斯林家庭以金色与绿色为节日主色，在客厅布置新月星光串灯、耶路撒冷圆顶清真寺造型摆件，门挂绿色“Al-Isra wal-Mi’raj”标识；清真寺举办夜间讲座，餐桌备椰枣、甜点与果汁招待礼拜者。',
    '宗教节庆消费集中在灯饰与家居布置，金色/绿色产品在马来与印尼市场走量；圆顶清真寺造型挂件、夜光星月装饰为差异化品类，提前一个月上架。',
    [['登霄夜门挂', 'isra miraj door banner', 'P1'],
     ['金色星月串灯', 'gold crescent fairy lights', 'P1'],
     ['圆顶清真寺摆件', 'dome of the rock decor', 'P1'],
     ['绿色拉旗', 'isra miraj banner green', 'P2'],
     ['登霄节气球', 'isra miraj balloons', 'P2'],
     ['新月造型灯笼', 'ramadan crescent lantern', 'P2'],
     ['伊斯兰墙贴', 'islamic wall stickers', 'P2'],
     ['阿语贺卡', 'isra miraj card arabic', 'P3'],
     ['金色纸屑', 'gold confetti party', 'P3'],
     ['节日礼品袋', 'eid gift bags gold', 'P3']]],

  ['东正教圣诞节', 'Orthodox Christmas', '01-07', '01-07', 'EU,ME',
    '儒略历12月25日，即公历1月7日，俄罗斯、塞尔维亚、乌克兰、白俄罗斯及中亚东正教群体的重要节日。1月6日平安夜实行圣诞斋戒，家中铺白色桌布、摆放干草象征马槽，以金色、白色与深红为节日主色，点燃长蜡烛；午夜全家前往教堂参加彻夜礼拜，7日享用十二道素斋晚宴并互赠礼物，街头张挂雪花灯饰与耶稣降生布景。',
    '东正教市场圣诞装饰窗口比天主教晚13天，可错峰清欧洲仓尾货；金色雪花、圣诞球与马槽摆件需求集中，关键词注意用 orthodox 提高精准度。',
    [['东正教圣诞球', 'orthodox christmas ornaments', 'P1'],
     ['金色雪花挂饰', 'gold snowflake decorations', 'P1'],
     ['圣诞长蜡烛', 'orthodox christmas candles', 'P1'],
     ['耶稣马槽摆件', 'nativity scene set', 'P2'],
     ['白色雪花窗贴', 'snowflake window clings', 'P2'],
     ['东正节气球', 'christmas balloons gold white', 'P2'],
     ['圣诞拉旗', 'christmas banner gold', 'P2'],
     ['圣诞树顶星', 'christmas tree topper star', 'P3'],
     ['圣诞贺卡', 'orthodox christmas card', 'P3'],
     ['金色礼物袋', 'christmas gift bags gold', 'P3']]],

  ['超级碗', 'Super Bowl Sunday', '02-08', '02-14', 'NA',
    '美国国家橄榄球联盟年度总决赛，常年在2月第二个星期日，是全美收视率最高的体育盛事。比赛从傍晚开始，家庭客厅改造成观赛主场：以两支决赛球队队色的气球、拉旗和横幅布置电视墙，餐桌摆满零食碗、饮品桶；人们穿着球队球衣或球星号码T恤，酒吧与餐厅架起大屏幕，中场秀期间举办主题派对，鸡翅、披萨与啤酒是标配，赛后还有赌局和颁奖话题。',
    '体育流量节点，1月决赛球队确定后迎来采购高峰；通用橄榄球品类提前上架，印有具体球队/Super Bowl LX字样的商品赛前必须清完。',
    [['橄榄球充气摆件', 'inflatable football decor', 'P1'],
     ['超级碗派对拉旗', 'super bowl party banner', 'P1'],
     ['球队球衣T恤', 'football jersey men', 'P1'],
     ['零食分格托盘', 'football snack tray', 'P1'],
     ['橄榄球气球', 'football balloons brown', 'P2'],
     ['饮品冷藏桶', 'beer bucket party', 'P2'],
     ['超级碗纸杯餐盘', 'super bowl party supplies', 'P2'],
     ['观赛助威毛巾', 'football fan towel', 'P2'],
     ['超级碗门挂', 'super bowl door hanger', 'P3'],
     ['派对拍照道具', 'super bowl photo booth props', 'P3']]],

  ['土拨鼠日', 'Groundhog Day', '02-02', '02-02', 'NA',
    '北美民间传统节日，每年2月2日，传说土拨鼠出洞：若看见自己的影子，冬天还将持续六周。节日色彩以棕色、深绿与冬日白为主，学校教室布置土拨鼠主题墙报、树洞手工与“春天还要等多久”倒计时卡片；宾州Punxsutawney举行盛大宣布仪式，家庭观看直播并购买土拨鼠毛绒玩偶，咖啡馆推出土拨鼠造型点心，是美国冬末趣味营销节点。',
    '客单以儿童教室装饰与毛绒玩偶为主，1月底进入高峰；可与春季花园主题合并备货，土拨鼠造型宠物用品也有小热度。',
    [['土拨鼠毛绒玩偶', 'groundhog stuffed animal', 'P1'],
     ['土拨鼠教室装饰', 'groundhog classroom decorations', 'P1'],
     ['土拨鼠头带手工', 'groundhog headband kids', 'P1'],
     ['土拨鼠主题横幅', 'groundhog day banner', 'P2'],
     ['春天倒计时海报', 'groundhog day poster', 'P2'],
     ['土拨鼠气球', 'groundhog balloons', 'P2'],
     ['土拨鼠贴纸', 'groundhog stickers kids', 'P3'],
     ['土拨鼠摆件', 'groundhog figurine', 'P3'],
     ['儿童绘本', 'groundhog day book kids', 'P3'],
     ['土拨鼠主题围裙', 'groundhog apron', 'P3']]],

  ['春节（华人新年）', 'Lunar New Year / Chinese New Year', '02-17', '02-06', 'SEA',
    '东南亚华人圈最重要的农历新年，马来西亚、新加坡、印尼均设公共假日（2026年2月17日）。节前数周大扫除、贴春联福字，牛车水与商场张满大红灯笼、桃花与年橘，以正红配金色为绝对主色；除夕吃团圆饭、鱼生捞起，初一穿红衣拜年发红包，街头举行舞狮舞龙与灯会，节令生肖吉祥物、红色年饼礼盒是走量爆款。',
    '红色品类节前两周爆发，生肖吉祥物与红包封销量最大；注意当年生肖主题，大件桃花年橘走本地仓，跨境主推轻量装饰与利是封。',
    [['大红灯笼', 'chinese new year lanterns red', 'P1'],
     ['生肖吉祥物', 'chinese zodiac plush', 'P1'],
     ['红包封套装', 'chinese red envelopes', 'P1'],
     ['春联福字套装', 'chinese couplets fu set', 'P1'],
     ['春节拉旗', 'lunar new year banner', 'P2'],
     ['舞狮摆件', 'lion dance decoration', 'P2'],
     ['金色年橘挂饰', 'kumquat tree ornaments', 'P2'],
     ['鱼生摆盘套装', 'lou sang platter set', 'P3'],
     ['红灯笼灯串', 'red lantern string lights', 'P3'],
     ['春节礼品袋', 'chinese new year gift bags', 'P3']]],

  ['威尼斯狂欢节', 'Venice Carnival (Carnevale di Venezia)', '02-17', '02-09', 'EU',
    '意大利威尼斯年度盛事，圣灰星期三前约十天开始、忏悔星期二落幕（2026年2月17日）。整座水城以金、黑、深蓝与酒红为节日色彩，圣马可广场挂满彩旗与吊灯；人们佩戴华丽全脸面具、三角帽和复古长袍，贡多拉船夫盛装划船，街头有杂耍与古典乐表演，假面舞会在宫廷酒店通宵举行，面具羽毛扇是必备道具。',
    '高端面具与复古服饰客单价高，节前两周集中出单；黑金配色羽毛面具辨识度最高，可搭配羽毛扇做组合套装。',
    [['威尼斯全脸面具', 'venetian masquerade mask', 'P1'],
     ['复古羽毛面具', 'venetian feather mask', 'P1'],
     ['假面舞会面具', 'masquerade mask women', 'P1'],
     ['狂欢节长袍', 'carnival costume medieval', 'P2'],
     ['羽毛折扇', 'feather hand fan', 'P2'],
     ['三角帽', 'tricorn hat costume', 'P2'],
     ['狂欢节气球', 'venice carnival balloons', 'P2'],
     ['金色面具手杖', 'masquerade stick mask', 'P3'],
     ['假面舞会装饰', 'masquerade party decorations', 'P3'],
     ['面具造型胸针', 'venetian mask brooch', 'P3']]],

  ['巴兰基亚狂欢节', 'Barranquilla Carnival', '02-14', '02-06', 'LATAM',
    '哥伦比亚巴兰基亚狂欢节，联合国非遗，圣灰星期三前的周六至周二举行（2026年2月14日开幕）。节日色彩浓烈，以红、黄、蓝、绿四色铺满大街小巷，Batalla de Flores花车大游行中舞者身着亮片舞裙、头戴羽毛冠抛洒鲜花；全城响起昆比亚鼓点，人们佩戴彩色面具与珠链参加街头Guacherna夜间游行，Marimonda小丑玩偶（长鼻花衣）是当地标志。',
    '哥伦比亚市场全年最大装扮窗口，羽毛冠与亮片舞裙为主推；Marimonda小丑周边竞争小，鼓乐打击乐器与多色珠链适合多件装。',
    [['羽毛花冠头饰', 'carnival feather headdress', 'P1'],
     ['亮片舞裙', 'sequin dance dress women', 'P1'],
     ['Marimonda小丑面具', 'marimonda mask', 'P1'],
     ['彩色珠链套装', 'carnival beads necklaces', 'P2'],
     ['狂欢节花束头饰', 'flower crown festival', 'P2'],
     ['昆比亚手鼓', 'cumbia drum instrument', 'P2'],
     ['彩色纸屑', 'carnival confetti colorful', 'P2'],
     ['狂欢节拉旗', 'barranquilla carnival banner', 'P3'],
     ['羽毛披肩', 'feather boa colorful', 'P3'],
     ['狂欢节手腕花', 'carnival wrist corsage', 'P3']]],

  ['普珥节', 'Purim', '03-03', '03-23', 'ME',
    '犹太历阿达尔月14日，纪念犹太民族在波斯免遭灭族，以色列全民狂欢（2026年3月3日）。节日色彩明快，以紫、金、红为主，学校与会堂布置王冠、权杖、波斯宫廷主题装饰；儿童穿着圣经人物或创意变装服，佩戴面具参加游行，成人诵读《以斯帖记》、互赠美食篮（Mishloach Manot），街头举办变装派对，会堂气球与拉旗装点一新。',
    '以色列儿童装扮节日，变装服与美食篮包装盒为刚需；王冠、权杖等宫廷主题在犹太市场精准度高，提前45天海运备货。',
    [['普珥节变装服', 'purim costume kids', 'P1'],
     ['儿童面具', 'purim masks kids', 'P1'],
     ['美食篮包装盒', 'mishloach manot boxes', 'P1'],
     ['金色王冠头饰', 'purim crown kids', 'P1'],
     ['普珥节拉旗', 'purim decorations banner', 'P2'],
     ['国王权杖道具', 'king scepter costume', 'P2'],
     ['普珥节气球', 'purim balloons', 'P2'],
     ['波斯主题服装', 'queen esther costume', 'P2'],
     ['普珥节贺卡', 'purim greeting card', 'P3'],
     ['派对噪音器', 'purim grogger noisemaker', 'P3']]],

  ['希腊独立日', 'Greek Independence Day', '03-25', '03-25', 'EU',
    '3月25日希腊国庆，纪念1821年脱离奥斯曼统治独立，同时适逢天使报喜日。全国以蓝白两色为节日主色，雅典宪法广场举行阅兵，卫城张挂蓝白灯光；学校组织游行，学生身穿蓝白校服、手持希腊小国旗，教堂举行感恩礼拜，家庭餐桌以蓝白桌旗、国旗气球布置，街头橱窗贴蓝白拉旗，海鲜与炸鳕鱼是当天传统食物。',
    '蓝白主题品类可与塞浦路斯、以色列共享供应链；国旗与蓝白装饰需求集中在3月中旬，宗教+国庆双主题客单稳定。',
    [['希腊小国旗', 'greek flag handheld', 'P1'],
     ['蓝白气球套装', 'blue white balloons', 'P1'],
     ['蓝白拉旗', 'greek independence banner', 'P2'],
     ['蓝白发饰', 'blue white hair bow', 'P2'],
     ['希腊国旗披风', 'greek flag cape', 'P2'],
     ['蓝白桌旗', 'blue white table runner', 'P2'],
     ['蓝白腕带', 'blue white wristbands', 'P3'],
     ['希腊徽章', 'greece button pin', 'P3'],
     ['蓝白灯串', 'blue white string lights', 'P3'],
     ['国庆纸袋糖果袋', 'blue white gift bags', 'P3']]],

  ['突尼斯独立日', 'Tunisia Independence Day', '03-20', '03-20', 'ME',
    '3月20日突尼斯独立纪念日，纪念1956年脱离法国独立。节日主色为国旗红与白，突尼斯城举行阅兵与授勋，街头悬挂红白国旗与横幅；学校布置独立日主题墙报，咖啡馆与商户悬挂彩灯，家庭以红白气球、星月标志装饰门庭，哈比卜·布尔吉巴大道举办庆祝游行，晚间还有音乐焰火表演。',
    '北非市场小众节日竞争小，红白星月主题品类与土耳其市场供应链通用；适合中小卖家测北非站点，提前一个月上架。',
    [['突尼斯国旗', 'tunisia flag', 'P1'],
     ['红白气球', 'red white balloons', 'P1'],
     ['红白拉旗', 'tunisia day banner', 'P2'],
     ['星月标志挂件', 'crescent star decoration red', 'P2'],
     ['红白腕带', 'red white wristbands', 'P2'],
     ['突尼斯徽章', 'tunisia pin badge', 'P2'],
     ['红白灯串', 'red white fairy lights', 'P3'],
     ['红白桌旗', 'red white table runner', 'P3'],
     ['国庆礼品袋', 'red white gift bags', 'P3'],
     ['突尼斯头巾配饰', 'tunisia scarf women', 'P3']]],

  ['墨西哥圣烛节', 'Día de la Candelaria', '02-02', '02-02', 'LATAM',
    '墨西哥圣诞季收官日，每年2月2日。三王节面包里吃到圣婴小人的人要在这天请客，家家户户把马槽中的圣婴像换上新衣，以白色、天蓝与金色为节日主色，给圣婴穿上绣花披风戴上小冠冕；清晨捧蜡烛参加教堂祝圣游行，之后回家摆 Tamale 玉米粽塔、Atole 热饮招待亲友，客厅马槽周围点缀白金色 Papel Picado 镂空旗。',
    '宗教节庆刚需：圣婴服饰、蜡烛与玉米粽蒸锅走量大；客单稳定但市场垂直，提前20天上架，主打墨西哥本地仓与美墨跨境。',
    [['圣婴绣花披风', 'nino dios outfit clothing', 'P1'],
     ['圣烛节长蜡烛', 'candelaria candles set', 'P1'],
     ['玉米粽大蒸锅', 'tamale steamer pot', 'P1'],
     ['圣婴小冠冕', 'baby jesus crown mini', 'P1'],
     ['白金镂空旗', 'white gold papel picado', 'P2'],
     ['教堂祈祷蜡烛', 'prayer candles catholic', 'P2'],
     ['迷你马槽摆件', 'mini nativity set', 'P2'],
     ['圣烛节气球', 'white gold balloons', 'P2'],
     ['圣烛节贺卡', 'candelaria greeting card', 'P3'],
     ['节日礼品袋', 'candelaria gift bags', 'P3']]],

  ['沙特建国日', 'Saudi Founding Day', '02-22', '02-22', 'ME',
    '沙特官方节日，纪念1727年沙特王国奠基，与9月绿色国庆不同，建国日主视觉为沙色、陶土棕与金色。利雅得各大商场以棕榈树、沙丘与传统陶瓮造型布置，男子穿米色长袍、披红格头巾跳 Ardah 剑舞，女子佩戴复古银饰展示 Najdi 村落文化；街头悬挂建国日徽章旗帜，晚间有传统音乐与烟火，咖啡馆供应豆蔻咖啡与椰枣宴。',
    '沙色/棕金主题与绿色国庆供应链区隔，剑舞道具、传统纹样饰品竞争小；节前两周集中爆发，适合做套装组合。',
    [['建国日门挂', 'saudi founding day banner', 'P1'],
     ['建国日主题T恤', 'founding day t shirt', 'P1'],
     ['沙金气球套装', 'beige gold balloons', 'P1'],
     ['Ardh剑舞道具剑', 'saudi ardah sword', 'P2'],
     ['阿拉伯咖啡壶', 'arabic dallah coffee pot', 'P2'],
     ['棕榈树摆件', 'palm tree table decor', 'P2'],
     ['建国日徽章', 'saudi founding day pin', 'P2'],
     ['传统纹样头巾', 'saudi heritage scarf', 'P3'],
     ['金色阿拉伯灯笼', 'gold arabic lantern', 'P3'],
     ['建国礼品袋', 'saudi national gift bags', 'P3']]],

  ['爱沙尼亚独立日', 'Estonian Independence Day', '02-24', '02-24', 'EU',
    '纪念1918年《独立宣言》发布，是爱沙尼亚最重要的国庆日。节日色彩为蓝、黑、白三色，塔林自由广场举行阅兵，总统府举办招待会；傍晚民众手持火把与蓝黑白灯笼参加火炬游行，家家户户窗台点燃蓝白蜡烛，学校张贴三色海报与国旗手工，餐厅供应国菜黑布丁与酸菜，晚间礼花照亮中世纪老城。',
    '波罗的海小众市场，蓝黑白三色品类供应链与立陶宛/拉脱维亚通用；窗台电子蜡烛安全款更受公寓家庭欢迎。',
    [['爱沙尼亚国旗', 'estonia flag', 'P1'],
     ['蓝黑白气球', 'blue black white balloons', 'P1'],
     ['独立日拉旗', 'estonia independence banner', 'P2'],
     ['窗台电子蜡烛', 'led window candles', 'P2'],
     ['国旗胸针', 'estonian flag pin', 'P2'],
     ['三色围巾', 'blue black white scarf', 'P2'],
     ['三色腕带', 'estonian wristbands', 'P3'],
     ['三色桌旗', 'estonian table runner', 'P3'],
     ['国旗手摇旗套装', 'handheld estonian flags', 'P3'],
     ['国庆礼品袋', 'blue black white gift bags', 'P3']]],

  ['科威特国庆', 'Kuwait National Day', '02-25', '02-25', 'ME',
    '科威特国庆为2月25日，次日26日为解放日，全国连庆两天。节日主色取自国旗的绿、白、红、黑，科威特地标大楼打出国旗灯光秀，街头车辆插满小旗、缠满绿白彩带巡游；孩子们在脸上画新月标志，穿着印有国旗图案的衣服，商场以气球拱门与彩灯布置，家庭到海滨大道野餐看烟火，随处可听到传统鼓乐。',
    '海湾高消费市场，车旗、脸彩与发光玩具是儿童刚需；适合做多件装与亲子套装，节前10天冲刺。',
    [['科威特国旗', 'kuwait flag', 'P1'],
     ['国庆绿白气球', 'kuwait balloons', 'P1'],
     ['汽车旗杆旗', 'kuwait car flag', 'P1'],
     ['国庆拉旗', 'kuwait national day banner', 'P1'],
     ['星月脸彩棒', 'crescent face paint sticks', 'P2'],
     ['发光腕带', 'led wristbands party', 'P2'],
     ['国旗胸针', 'kuwait flag pin', 'P2'],
     ['国庆桌旗', 'kuwait table runner', 'P2'],
     ['彩色纸屑', 'green confetti party', 'P3'],
     ['国庆礼品袋', 'kuwait gift bags', 'P3']]],

  ['多米尼加独立日', 'Dominican Independence Day', '02-27', '02-27', 'LATAM',
    '多米尼加共和国1844年脱离海地独立的纪念日，每年2月27日，海外侨民（尤其美国纽约、迈阿密）同步庆祝。节日色彩为国旗的红、白、蓝，圣多明各举行盛大阅兵与花车游行，学校组织学生穿红蓝白校服游行；家门口悬挂国旗，餐桌铺国旗桌布，供应 Mangu 香蕉泥与炸猪皮，晚间海滨燃放烟火，街头有 Merengue 乐队巡演。',
    '美国西语侨民市场容量大，红蓝白品类与美国国庆供应链部分通用；多米尼加专属国旗图案产品溢价高。',
    [['多米尼加国旗', 'dominican republic flag', 'P1'],
     ['红蓝白气球', 'red blue white balloons', 'P1'],
     ['独立日拉旗', 'dominican independence banner', 'P1'],
     ['国旗披风', 'dominican flag cape', 'P2'],
     ['手摇小旗套装', 'handheld dominican flags', 'P2'],
     ['国旗腕带', 'dominican wristbands', 'P2'],
     ['国旗胸针', 'dominican flag pin', 'P2'],
     ['汽车旗杆旗', 'dominican car flag', 'P3'],
     ['红蓝白桌旗', 'dominican table runner', 'P3'],
     ['独立日礼品袋', 'dominican gift bags', 'P3']]],

  ['保加利亚三月节', 'Baba Marta Day', '03-01', '03-01', 'EU',
    '保加利亚千年民俗节日，3月1日迎接“三月奶奶” Baba Marta。人们互相赠送红白两色 Martenitsa 护身符——红白人偶 Pizho 与 Penda、绒球穗带，佩戴在胸前或手腕，直到看见第一只鹳或燕子，再把它挂到开花的树枝上祈求健康。节日色彩就是纯粹的红白两色，集市挂满红白绒线饰品，学校教孩子编织三月结，家中摆放陶土“三月奶奶”玩偶。',
    '红白编织饰品客单低但走量极大，可做多件装全家套餐；绒球、流苏配件与手工DIY材料包在欧洲站受欢迎。',
    [['三月结手绳', 'martenitsa bracelet', 'P1'],
     ['红白绒球人偶', 'martenitsa pizho penda', 'P1'],
     ['红白流苏胸针', 'martenitsa pin tassel', 'P1'],
     ['三月节贺卡', 'baba marta card', 'P2'],
     ['红白气球套装', 'red white balloons', 'P2'],
     ['三月奶奶玩偶', 'baba marta doll', 'P2'],
     ['编织DIY材料包', 'martenitsa making kit', 'P2'],
     ['红白穗带发饰', 'red white tassel hair clip', 'P3'],
     ['开花树枝挂饰', 'blossom tree decorations', 'P3'],
     ['三月节礼品袋', 'red white gift bags', 'P3']]],

  ['立陶宛恢复独立日', 'Lithuanian Restoration of Independence Day', '03-11', '03-11', 'EU',
    '纪念1990年3月11日立陶宛成为首个宣布脱离苏联独立的加盟共和国。节日主色为黄、绿、红三色，维尔纽斯独立广场举行升旗与阅兵， Gediminas 城堡打出三色灯光；人们佩戴三色胸花与腕带参加音乐会，学校布置独立主题展览，街头有手工艺品集市，傍晚点燃三色烟花，咖啡馆供应立陶宛蜂蜜啤酒。',
    '波罗的海三国节日供应链通用，黄绿红配色注意与玻利维亚区分；加入立陶宛国徽 Vytis 骑士元素提高精准度。',
    [['立陶宛国旗', 'lithuania flag', 'P1'],
     ['黄绿红气球', 'yellow green red balloons', 'P1'],
     ['独立日拉旗', 'lithuania independence banner', 'P2'],
     ['骑士国徽胸针', 'lithuania vytis pin', 'P2'],
     ['三色腕带', 'lithuanian wristbands', 'P2'],
     ['三色围巾', 'lithuania tricolor scarf', 'P2'],
     ['三色桌旗', 'lithuania table runner', 'P3'],
     ['手摇小旗套装', 'handheld lithuanian flags', 'P3'],
     ['黄绿红灯串', 'lithuania string lights', 'P3'],
     ['独立日礼品袋', 'lithuania gift bags', 'P3']]],

  ['匈牙利民族日', 'Hungarian National Day (1848 Revolution)', '03-15', '03-15', 'EU',
    '纪念1848年匈牙利反对哈布斯堡王朝的革命与独立战争。节日色彩为红、白、绿三色，布达佩斯国会大厦前举行升旗典礼，人们几乎人人佩戴红白绿三色圆形 Kokárda 布花胸章；市民登上布达城堡参加朗诵与军乐表演，多瑙河畔有民俗集市与传统美食 Lángos 炸饼，傍晚燃放烟花，博物馆当天免费开放。',
    '三色 Kokárda 胸章是全民刚需、当天佩戴率极高，轻便好走量；注意与意大利/墨西哥等红绿白市场做图案区隔。',
    [['匈牙利三色胸章', 'hungarian kokarda badge', 'P1'],
     ['匈牙利国旗', 'hungary flag', 'P1'],
     ['红白绿气球', 'red white green balloons', 'P1'],
     ['民族日拉旗', 'hungary national day banner', 'P2'],
     ['三色腕带', 'hungarian wristbands', 'P2'],
     ['刺绣民族风围裙', 'hungarian embroidered apron', 'P2'],
     ['三色绶带', 'hungarian tricolor sash', 'P2'],
     ['手摇小旗套装', 'handheld hungarian flags', 'P3'],
     ['红白绿桌旗', 'hungary table runner', 'P3'],
     ['民族日礼品袋', 'hungary gift bags', 'P3']]],

  ['法雅节', 'Las Fallas', '03-19', '03-19', 'EU',
    '西班牙瓦伦西亚年度火节，3月15日起全城摆放巨型纸偶 Ninot 雕塑（讽刺名人与时事），每天午后市政厅广场举行震耳欲聋的 Mascletà 爆竹秀，18日深夜有灯火烟花秀，19日圣约瑟夫日夜间 Cremà 焚烧所有法雅人偶，火光映红全城。节日色彩为金、红与象牙白，Fallera 女子梳发髻、插金梳、穿金线刺绣长裙向圣母献花，鲜花拼成巨大圣母披风。',
    '节后即焚的属性让节日纪念品在游客中热销；金梳、折扇、小纸偶冰箱贴为主推，安全型派对烟花适合家庭场景。',
    [['法雅人偶冰箱贴', 'fallas ninot magnet', 'P1'],
     ['Fallera金梳发饰', 'fallera gold hair comb', 'P1'],
     ['瓦伦西亚折扇', 'valencian hand fan', 'P1'],
     ['安全派对烟花', 'party poppers safe fireworks', 'P2'],
     ['法雅人偶钥匙扣', 'ninot keychain', 'P2'],
     ['法雅节拉旗', 'fallas party banner', 'P2'],
     ['儿童Fallera裙', 'fallera costume girls', 'P2'],
     ['火焰造型装饰', 'flame party decorations', 'P3'],
     ['鲜花发夹套装', 'flower hair pins spain', 'P3'],
     ['瓦伦西亚明信片', 'valencia souvenir postcard', 'P3']]],

  ['巴基斯坦日', 'Pakistan Day', '03-23', '03-23', 'ME',
    '纪念1940年拉合尔决议（穆斯林联盟提出建国）与1956年巴基斯坦首部宪法。伊斯兰堡举行盛大阅兵，展示战机与导弹，节日主色为国旗的深绿与白，新月五角星标志无处不在；大街小巷张挂绿白彩旗与灯笼，孩子们穿绿色新衣、脸上画星月，学校举办演讲与诗朗诵，家庭走亲访友互送甜点，晚间各地放烟火庆祝。',
    '两亿人口市场，绿白星月品类与穆斯林节庆供应链通用；儿童绿色服饰与脸彩走量，国旗大件走本地仓。',
    [['巴基斯坦国旗', 'pakistan flag', 'P1'],
     ['绿白气球套装', 'green white balloons', 'P1'],
     ['星月脸彩棒', 'crescent star face paint', 'P1'],
     ['巴基斯坦日拉旗', 'pakistan day banner', 'P1'],
     ['儿童绿色Kurta', 'green kurta kids', 'P2'],
     ['星月发光胸针', 'crescent star led pin', 'P2'],
     ['绿白腕带', 'pakistan wristbands', 'P2'],
     ['绿白灯笼', 'green white lanterns', 'P2'],
     ['手摇小旗套装', 'handheld pakistan flags', 'P3'],
     ['节日礼品袋', 'green white gift bags', 'P3']]],

  ['逾越节', 'Passover (Pesach)', '04-02', '04-22', 'ME',
    '犹太教三大朝圣节之一，纪念以色列人出埃及，节期7天（以色列）至8天（海外），家宴 Seder 在首夜举行。节日色彩以白、银、深紫与酒红为主，餐桌铺白色桌布，摆 Seder Plate 六格餐盘、无酵饼盒与银杯 Elijah 杯，家中收尽一切发酵食品；家人头戴圆帽诵读哈加达，门挂“Happy Passover”装饰，厨房换上逾越节专用餐具，桌中央点缀白花与葡萄藤。',
    'Seder 餐具与无酵饼周边是节日刚需，深紫酒红配色辨识度高；面向以色列与北美犹太社区，提前45天海运备货。',
    [['逾越节六格餐盘', 'passover seder plate', 'P1'],
     ['无酵饼盒', 'matzah holder box', 'P1'],
     ['以利亚银杯', 'elijah cup silver', 'P1'],
     ['逾越节拉旗', 'happy passover banner', 'P1'],
     ['逾越节桌布', 'passover tablecloth white', 'P2'],
     ['酒红色餐巾环', 'passover napkin rings', 'P2'],
     ['逾越节气球', 'passover balloons', 'P2'],
     ['儿童哈加达绘本', 'passover haggadah kids', 'P2'],
     ['逾越节贺卡', 'passover greeting cards', 'P3'],
     ['无酵饼造型抱枕', 'matzah pillow cover', 'P3']]],

  ['耶稣受难日', 'Good Friday', '04-03', '03-26', 'EU,LATAM',
    '复活节前的星期五，纪念耶稣受难，是基督教世界最肃穆的节日。教堂撤去鲜花、祭坛覆盖黑布或紫布，以深紫、黑色与原木色为主，信众佩戴十字架参加苦路游行，巴西、菲律宾等国信徒重演十四处苦路；家中点燃长蜡烛、摆荆棘冠与十字架装饰，禁食不食肉，餐桌只上十字热面包与鱼汤，商店橱窗以紫纱与白百合布置，午后三时全国鸣钟默祷。',
    '与复活节彩蛋品类形成区隔，深紫色宗教布艺、十字架装饰为主推；热面包模具与紫纱桌旗在拉美市场稳定出单。',
    [['木质十字架摆件', 'wooden standing cross', 'P1'],
     ['深紫色教堂纱幔', 'purple liturgical cloth', 'P1'],
     ['荆棘冠摆件', 'crown of thorns decor', 'P1'],
     ['十字热面包模具', 'hot cross bun pan', 'P2'],
     ['受难日长蜡烛', 'good friday candles', 'P2'],
     ['白百合花束', 'white lilies artificial', 'P2'],
     ['受难日拉旗', 'good friday banner', 'P2'],
     ['祈祷披肩', 'catholic prayer shawl', 'P3'],
     ['受难日贺卡', 'good friday card', 'P3'],
     ['紫色蜡烛花环', 'purple candle wreath', 'P3']]],

  ['却克里王朝纪念日', 'Chakri Memorial Day', '04-06', '04-06', 'SEA',
    '泰国法定假日，纪念却克里王朝（曼谷王朝）1782年开国及历代国王，拉玛一世曾建都曼谷。节日主色为王室黄与金色，曼谷大皇宫与玉佛寺举行宗教仪式，王室成员赴王家纪念柱献花圈；民众穿上黄色衣服入寺布施，向拉玛五世骑马铜像敬献花环，街道悬挂王旗与黄色彩旗，家中摆国王画像与万寿菊花环，商场橱窗以金箔莲花布置。',
    '泰国王室主题节点，黄色品类与国王生日/宋干节供应链通用；已故国王纪念周边注意选用官方通用的敬意设计。',
    [['却克里纪念花环', 'marigold garland thai', 'P1'],
     ['王室黄丝带', 'thai royal yellow ribbon', 'P1'],
     ['金色拉旗', 'chakri day banner gold', 'P2'],
     ['莲花金箔供盘', 'gold lotus tray', 'P2'],
     ['黄色折叠伞', 'yellow umbrella thailand', 'P2'],
     ['国王纪念胸针', 'thai king rama pin', 'P2'],
     ['黄色腕带', 'yellow wristbands', 'P3'],
     ['香薰蜡烛套装', 'thai scented candle set', 'P3'],
     ['黄白气球', 'yellow gold balloons', 'P3'],
     ['王室礼品袋', 'gold gift bags thai', 'P3']]],

  ['荷兰国王节', 'King’s Day (Koningsdag)', '04-27', '04-27', 'EU',
    '荷兰最狂热的全国派对，庆祝威廉-亚历山大国王生日（4月27日）。整个国家变成橙色海洋：运河上挤满橙色小船和水上派对，阿姆斯特丹街头摆摊举行全民跳蚤市场 Vrijmarkt，人们戴橙色假发、橙色皇冠、羽毛 boa，脸上涂红白蓝国旗色；广场响起电子乐，啤酒与橙色甜点畅销，孩子们穿橙衣街头卖艺，全城没有一辆汽车，处处是橙色气球与三角旗。',
    '橙色是唯一关键词：假发、皇冠、T恤等轻量装扮品节前一周爆发；海运提前45天，可搭配荷兰国旗红白蓝做组合。',
    [['橙色爆炸假发', 'orange afro wig', 'P1'],
     ['橙色皇冠发箍', 'orange crown headband', 'P1'],
     ['国王节橙色T恤', 'kings day orange shirt', 'P1'],
     ['橙色羽毛围巾', 'orange feather boa', 'P1'],
     ['橙色太阳镜', 'orange sunglasses party', 'P2'],
     ['橙色三角拉旗', 'orange bunting flags', 'P2'],
     ['荷兰国旗脸彩', 'red white blue face paint', 'P2'],
     ['橙色啤酒杯', 'orange beer cup', 'P2'],
     ['橙色长袜套装', 'orange socks stripes', 'P3'],
     ['派对橙色手环', 'orange wristbands', 'P3']]],

  ['墨西哥儿童节', 'Día del Niño (Children’s Day)', '04-30', '04-30', 'LATAM',
    '墨西哥法定儿童节，4月30日，是玩具、童装和糖果全年最旺的销售窗口之一。学校停课半天举办嘉年华：教室挂满彩色气球与拉旗，孩子们穿便装参加游戏、抽奖和 Piñata 皮纳塔砸糖；家长带孩子去游乐场、吃蛋糕，餐厅推出儿童免单活动，商场布置卡通人偶合影区，糖果色（粉、黄、青、薄荷绿）是主视觉，家庭聚会餐桌摆满纸杯蛋糕与糖果袋。',
    '玩具类卖家必争节点，皮纳塔与糖果袋为家庭聚会刚需；注意与圣诞、三王节玩具季错峰，轻量玩具走跨境、大件走本地仓。',
    [['皮纳塔糖果罐', 'pinata mexican kids', 'P1'],
     ['儿童节糖果袋', 'goodie bags kids', 'P1'],
     ['卡通气球套装', 'colorful balloons kids', 'P1'],
     ['儿童嘉年华拉旗', 'childrens day banner', 'P2'],
     ['派对吹龙套装', 'party blowers horns', 'P2'],
     ['彩色蛋糕插牌', 'cupcake toppers kids', 'P2'],
     ['儿童皇冠头饰', 'birthday crown kids', 'P2'],
     ['临时贴纸纹身', 'temporary tattoos kids', 'P3'],
     ['泡泡机玩具', 'bubble machine party', 'P3'],
     ['儿童节礼品盒', 'kids gift boxes colorful', 'P3']]],

  ['越南统一日', 'Vietnamese Reunification Day', '04-30', '04-30', 'SEA',
    '4月30日是越南“南方解放日”，纪念1975年南北统一，与5月1日劳动节相连形成四天长假，是越南人出行、办婚礼和装修的高峰。街头张挂金星红旗与红横幅，胡志明市举行阅兵与游行，节日主色为红与金；家庭利用长假布置新居、采购家电与婚庆用品，商场以红色拱门和金箔装饰，景点与咖啡馆人满为患，晚间有烟火表演。',
    '长假带动家居、婚庆与出游消费，红色节庆品类与春节供应链通用；家电装饰大件走本地仓，饰品小物适合跨境。',
    [['金星红旗', 'vietnam flag', 'P1'],
     ['红金气球拱门', 'red gold balloon garland', 'P1'],
     ['统一日拉旗', 'reunification day banner', 'P2'],
     ['婚庆喜字套装', 'vietnamese wedding decor', 'P2'],
     ['新居入伙挂件', 'housewarming decoration vietnam', 'P2'],
     ['金色桌旗', 'gold table runner', 'P2'],
     ['红色灯笼挂饰', 'red lanterns small', 'P3'],
     ['旅行收纳套装', 'travel organizer set', 'P3'],
     ['红金纸屑', 'red gold confetti', 'P3'],
     ['节日礼品袋', 'red gold gift bags', 'P3']]],

  ['俄罗斯胜利日', 'Victory Day (Russia)', '05-09', '05-09', 'EU',
    '俄罗斯及独联体最隆重的纪念日，纪念1945年对德战争胜利。莫斯科红场举行阅兵，节日主色为圣乔治丝带的橙黑两色，配以红旗；人们把橙黑丝带系在胸前、书包和车镜上，向烈士墓献红色康乃馨，傍晚放和平鸽与烟火，大街小巷挂满“胜利日”横幅与红军旗；老兵穿军装挂满勋章出席纪念会，家庭看《这里黎明静悄悄》等战争老电影。',
    '橙黑圣乔治丝带与红康乃馨是全民刚需，轻便好走量；历史纪念题材严肃，避免娱乐化设计，主打庄重通用元素。',
    [['圣乔治丝带', 'saint george ribbon', 'P1'],
     ['红色康乃馨花束', 'red carnations artificial', 'P1'],
     ['胜利日胸章', 'victory day badge', 'P1'],
     ['胜利日拉旗', 'victory day banner', 'P2'],
     ['橙黑腕带', 'orange black wristband', 'P2'],
     ['红军旗小旗', 'red army flag mini', 'P2'],
     ['和平鸽挂饰', 'white peace dove decor', 'P2'],
     ['橙黑气球', 'orange black balloons', 'P3'],
     ['纪念蜡烛', 'memorial candle led', 'P3'],
     ['老兵主题贺卡', 'victory day card', 'P3']]],

  ['挪威宪法日', 'Norwegian Constitution Day (Syttende Mai)', '05-17', '05-17', 'EU',
    '挪威1814年宪法签署纪念日，也是全球最童趣的国庆：奥斯陆举行小学生游行，孩子们挥舞国旗、吹号打鼓穿过王宫，王室在阳台挥手。节日主色为国旗红、蓝、白，人人穿 Bunad 刺绣民族盛装，胸前别国旗徽章；街头到处是腊肠、冰淇淋与气泡水，女孩头发系红白蓝丝带，家中餐桌摆奶油蛋糕与国旗牙签，家庭聚会从清晨香槟早餐持续到夜晚。',
    '国旗小物与派对餐饮周边需求集中，民族风刺绣服饰客单高；红蓝白通用素材可做挪威专属图案提高溢价。',
    [['挪威手摇国旗', 'norwegian flag handheld', 'P1'],
     ['红蓝白气球', 'red blue white balloons', 'P1'],
     ['宪法日拉旗', 'norway constitution banner', 'P2'],
     [' Bunad民族胸针', 'norwegian bunad brooch', 'P2'],
     ['国旗牙签插牌', 'norway flag cupcake picks', 'P2'],
     ['儿童国旗斗篷', 'norwegian flag cape kids', 'P2'],
     ['三色丝带发饰', 'ribbon hair bows girls', 'P3'],
     ['红蓝白腕带', 'norway wristbands', 'P3'],
     ['挪威国旗T恤', 'norway flag t shirt', 'P3'],
     ['国庆糖果袋', 'norway party favor bags', 'P3']]],

  ['犹太五旬节', 'Shavuot', '05-22', '06-11', 'ME',
    '犹太教三大节之一，纪念上帝在西奈山授予摩西十诫，节期两天。节日以白色为绝对主色，会堂与家中铺满鲜花绿叶——纪念大卫王与西奈花香，人们穿全白衣服参加彻夜诵经；餐桌上必吃奶酪蛋糕、千层面等乳制品，门框挂白色花环，窗户贴十诫主题贴纸，孩子收到带花饰的新 Torah 小卷轴礼物，社区举办奶制品烘焙大赛。',
    '白色花艺装饰与乳制品烘焙周边是特色品类，与逾越节、光明节共享犹太市场客户；鲜花用品主推不易坏的仿真花。',
    [['白色鲜花花环', 'white flower garland', 'P1'],
     ['芝士蛋糕模具', 'cheesecake pan springform', 'P1'],
     ['西奈十诫摆件', 'ten commandments decor', 'P1'],
     ['全白祈祷披肩', 'white tallit prayer shawl', 'P2'],
     ['绿叶窗贴', 'green leaves window clings', 'P2'],
     ['五旬节拉旗', 'shavuot banner', 'P2'],
     ['儿童Torah卷轴', 'toy torah scroll kids', 'P2'],
     ['白色花篮', 'white flower basket', 'P3'],
     ['乳制品食谱书', 'dairy cookbook jewish', 'P3'],
     ['白色气球套装', 'white balloons party', 'P3']]],

  ['圣克鲁桑节', 'Santacruzan / Flores de Mayo', '05-31', '05-31', 'SEA',
    '菲律宾5月鲜花月的收官盛典，融合天主教与民俗，纪念圣海伦娜寻获真十字架。月末大游行在黄昏开始，少女们身穿白色礼服扮演历代王后，最后一位“艾琳娜皇后”手捧十字架、头戴璀璨皇冠，伴随鲜花拱门与烛光行进；教堂整月以鲜花和棕榈装饰，节日色彩为象牙白、香槟金与玫瑰粉，女孩们戴着天使翅膀，沿街抛洒花瓣，散场后家庭共享 Halo-halo 刨冰。',
    '皇冠、天使翅膀与鲜花头饰是少女刚需，白色礼服配饰客单高；与圣诞、复活节装扮品类共享供应链，主打菲律宾与海外菲佣市场。',
    [['皇后皇冠头饰', 'santacruzan tiara crown', 'P1'],
     ['天使翅膀道具', 'angel wings costume', 'P1'],
     ['鲜花拱门饰', 'flower arch decoration', 'P1'],
     ['白金色长手套', 'white long gloves girls', 'P2'],
     ['玫瑰花瓣抛洒包', 'rose petals artificial', 'P2'],
     ['烛光大游行灯笼', 'processional candle lantern', 'P2'],
     ['象牙白礼服裙', 'white gown girls', 'P2'],
     ['鲜花花环头饰', 'flower crown headband', 'P3'],
     ['圣克鲁桑拉旗', 'santacruzan banner', 'P3'],
     ['十字权杖道具', 'cross scepter costume', 'P3']]],

  ['意大利共和国日', 'Italian Republic Day (Festa della Repubblica)', '06-02', '06-02', 'EU',
    '纪念1946年公投废除君主制、建立共和国，意大利6月2日国庆。罗马帝国大道举行阅兵，总统向无名战士墓献花圈，三色箭飞行表演机尾喷出绿白红三色烟雾；节日主色为绿、白、红，街头挂满三色旗与三角旗，餐厅露台摆三色意面造型甜点，家庭在阳台悬挂国旗，傍晚广场有军乐演奏与烟花，博物馆免费开放。',
    '绿白红三色品类与墨西哥/匈牙利等市场共享素材，加入意大利地图或比萨斜塔图案做区隔；国旗披风与脸彩在派对场景走量。',
    [['意大利国旗', 'italy flag', 'P1'],
     ['绿白红气球', 'green white red balloons', 'P1'],
     ['共和国日拉旗', 'italy republic day banner', 'P2'],
     ['国旗披风', 'italian flag cape', 'P2'],
     ['三色腕带', 'italy wristbands', 'P2'],
     ['国旗脸彩棒', 'green white red face paint', 'P2'],
     ['手摇小旗套装', 'handheld italian flags', 'P3'],
     ['三色桌旗', 'italy table runner', 'P3'],
     ['国旗造型领结', 'italian flag bow tie', 'P3'],
     ['国庆糖果袋', 'italy party favor bags', 'P3']]],

  ['菲律宾独立日', 'Philippine Independence Day', '06-12', '06-12', 'SEA',
    '纪念1898年脱离西班牙殖民、发表《独立宣言》。黎刹公园举行升旗与阅兵，节日色彩为国旗的蓝、红、白与太阳金；街头挂满红蓝彩旗与太阳光芒拉旗，学校组织民族服装日，学生穿 Barong Tagalog 刺绣礼服游行；家庭餐桌上摆 Adobo 烧鸡与 Halo-halo，海外菲侨社区同步游行，商场以三色气球拱门和金太阳装饰，晚间燃放烟火。',
    '菲律宾一亿人口+海外侨民双市场，太阳光芒图案辨识度高；Barong 刺绣服装客单高，轻量装饰走跨境。',
    [['菲律宾国旗', 'philippines flag', 'P1'],
     ['红蓝白气球', 'blue red white balloons', 'P1'],
     ['金太阳拉旗', 'philippine independence banner', 'P1'],
     ['太阳光芒脸贴', 'sun star face stickers', 'P2'],
     ['国旗腕带', 'philippines wristbands', 'P2'],
     ['金太阳胸针', 'philippine sun pin', 'P2'],
     ['手摇小旗套装', 'handheld philippine flags', 'P2'],
     ['Barong刺绣礼服', 'barong tagalog men', 'P3'],
     ['红蓝白桌旗', 'philippines table runner', 'P3'],
     ['独立日礼品袋', 'philippines gift bags', 'P3']]],

  ['俄罗斯日', 'Russia Day', '06-12', '06-12', 'EU',
    '俄罗斯联邦国庆，纪念1990年《国家主权宣言》通过。莫斯科红场举办大型音乐会与庆典，节日主色为白蓝红三色，克里姆林宫打出三色灯光；街头悬挂国旗与三色花环，公园举行亲子活动与民俗集市，人们穿印有国旗图案的T恤参加露天派对，家庭在阳台挂三色旗，晚间全国同步燃放烟花，年轻人流行戴三色发带。',
    '三色品类与法国/荷兰等欧洲市场共享供应链，但要做俄语标识差异化；国旗T恤与腕带轻便好走量。',
    [['俄罗斯国旗', 'russia flag', 'P1'],
     ['白蓝红气球', 'white blue red balloons', 'P1'],
     ['俄罗斯日拉旗', 'russia day banner', 'P2'],
     ['国旗T恤', 'russian flag t shirt', 'P2'],
     ['三色腕带', 'russia wristbands', 'P2'],
     ['三色发带', 'white blue red headband', 'P2'],
     ['国旗胸针', 'russia flag pin', 'P3'],
     ['三色花环', 'russian flag lei', 'P3'],
     ['手摇小旗套装', 'handheld russian flags', 'P3'],
     ['国庆礼品袋', 'russia gift bags', 'P3']]],

  ['美国国旗日', 'Flag Day (USA)', '06-14', '06-14', 'NA',
    '纪念1777年星条旗正式确立，虽非联邦假日但全美庆祝，也是美国陆军建军日。节日色彩就是红白蓝，居民区挂出国旗、门廊缠星条旗花环，学校要求穿星条元素服装并举行升旗；社区举行爱国游行与野餐，餐桌摆国旗餐盘与星条旗纸杯蛋糕，人们佩戴国旗徽章，傍晚在公园举行露天音乐会，童子军组织退役国旗焚烧礼。',
    '夹在独立日备货周期内，可做一波补单；星条旗花环、门挂与餐盘为主推，与7月4日品类完全通用。',
    [['星条旗花环门挂', 'flag day wreath', 'P1'],
     ['红白蓝气球', 'red white blue balloons', 'P1'],
     ['国旗日拉旗', 'flag day banner', 'P1'],
     ['星条旗餐盘套装', 'patriotic plates napkins', 'P2'],
     ['国旗徽章胸针', 'american flag pin', 'P2'],
     ['红白蓝腕带', 'patriotic wristbands', 'P2'],
     ['国旗造型太阳镜', 'flag sunglasses novelty', 'P2'],
     ['星条旗纸杯蛋糕插牌', 'flag cupcake toppers', 'P3'],
     ['国旗头带', 'patriotic headband', 'P3'],
     ['爱国糖果袋', 'flag favor bags', 'P3']]],

  ['北欧仲夏节', 'Midsummer', '06-19', '06-25', 'EU',
    '瑞典、芬兰、挪威、丹麦最重要的夏日庆典，在6月19至25日之间的星期五举行。人们到乡间竖起缠绕绿叶与鲜花的五月柱，围着它跳青蛙舞，节日色彩为草地绿、野花黄与天空蓝；女孩头戴自制野花环，穿白连衣裙配蓝丝带，餐桌摆腌鲱鱼、新土豆与草莓奶油蛋糕，大人痛饮调味烈酒，晚间点燃篝火，瑞典国旗蓝黄色彩点缀庭院。',
    '野花环、五月柱DIY与白色连衣裙周边为刚需；花环材料包与蓝黄丝带走量，注意北欧消费者偏好天然材质。',
    [['仲夏野花花环', 'midsummer flower crown', 'P1'],
     ['五月柱DIY套装', 'midsummer maypole kit', 'P1'],
     ['白色棉麻连衣裙', 'white summer dress women', 'P1'],
     ['绿叶花环门挂', 'green leaf wreath', 'P2'],
     ['草莓蛋糕架', 'strawberry cake stand', 'P2'],
     ['瑞典国旗拉旗', 'swedish flag banner', 'P2'],
     ['蓝黄丝带发饰', 'blue yellow ribbon', 'P2'],
     ['野花环材料包', 'flower crown making kit', 'P3'],
     ['户外野餐布', 'picnic blanket outdoor', 'P3'],
     ['蜜蜂造型蜡烛', 'bee shaped candles', 'P3']]],

  ['骄傲月', 'Pride Month', '06-28', '06-27', 'NA',
    '每年6月为全球LGBTQ+骄傲月，月末周日举行大游行（纽约、旧金山、洛杉矶、伦敦同步），纪念石墙事件。节日色彩为六色彩虹，街道变成彩虹海洋：人们穿彩虹背带、亮片热裤、羽毛装饰参加游行，脸上涂彩虹色，沿街派发彩虹糖果与安全套；广场有露天演出和市集，酒吧举办变装秀，商场橱窗挂彩虹旗，家庭带孩子参加彩虹亲子跑，包装成“爱与平等”主题。',
    '彩虹是全年通用元素、6月达到顶峰，轻量饰品与装扮品出单集中；设计走正能量包容路线，避免低俗化。',
    [['六色彩虹旗', 'rainbow pride flag', 'P1'],
     ['彩虹背带吊带', 'rainbow suspenders', 'P1'],
     ['彩虹脸彩棒', 'rainbow face paint', 'P1'],
     ['彩虹羽毛围巾', 'rainbow feather boa', 'P1'],
     ['彩虹串灯', 'rainbow string lights', 'P2'],
     ['彩虹袜子', 'rainbow socks stripes', 'P2'],
     ['彩虹腕带', 'rainbow wristbands', 'P2'],
     ['彩虹亮片短裤', 'rainbow sequin shorts', 'P2'],
     ['彩虹气球套装', 'rainbow balloons', 'P3'],
     ['彩虹主题礼品袋', 'rainbow gift bags', 'P3']]],

  ['圣费尔明奔牛节', 'San Fermín Festival', '07-06', '07-06', 'EU',
    '西班牙潘普洛纳年度盛事，7月6日正午市政厅礼花 Chupinazo 宣告开幕，持续至14日。每天清晨8点公牛沿石板小巷奔往斗牛场，穿全白衣裤、系红领巾红腰带的人群在公牛前奔跑，是全球最惊险的民俗；节日色彩为全白配圣费尔明红，广场摆满红酒袋，人们互洒红酒、高举报纸卷，阳台挂满红领巾，夜晚有烟花与街头乐队，脖子上挂的大蒜串与红方巾是标志装扮。',
    '白色亚麻衣裤+红领巾红腰带套装是刚需，客单低但走量大；红酒袋与报纸卷造型道具为特色品类，主推西班牙游客。',
    [['奔牛节全白套装', 'san fermin white outfit', 'P1'],
     ['红色领巾方巾', 'red neckerchief pañuelo', 'P1'],
     ['红色布腰带', 'red faja sash', 'P1'],
     ['西班牙红酒袋', 'spanish bota wine bag', 'P2'],
     ['奔牛节红T恤', 'running bulls t shirt', 'P2'],
     ['红色腕带套装', 'red wristbands', 'P2'],
     ['公牛造型帽子', 'bull horns hat', 'P2'],
     ['红酒造型派对杯', 'wine party cups', 'P3'],
     ['红色方巾脸彩', 'red bandana face cover', 'P3'],
     ['奔牛节礼品袋', 'red white gift bags', 'P3']]],

  ['那达慕大会', 'Naadam Festival', '07-11', '07-11', 'ME',
    '蒙古国“男儿三艺”国庆，7月11日至13日在全国举行，纪念1921年革命。乌兰巴托中央广场举行开幕阅兵与骑兵仪仗，节日色彩为草原蓝、奶白与鎏金；男子穿丝绸德勒长袍、系宽大绸腰带，摔跤手穿奇特的昭德格坎肩入场，弓箭手戴骨质扳指，儿童参加赛马；草原上搭起白色蒙古包，牧民煮整羊、熬奶茶招待宾客，姑娘戴银鎏金头饰，黄昏马头琴声伴着篝火。',
    '草原民族风情品类与内蒙古市场相通，丝绸腰带、小弓玩具与银饰为主推；工艺品主推真正的民族纹样，客单可做高。',
    [['迷你蒙古包模型', 'mongolian ger model', 'P1'],
     ['儿童小弓箭玩具', 'kids bow arrow toy', 'P2'],
     ['丝绸宽腰带', 'mongolian silk sash', 'P2'],
     ['摔跤手帽摆件', 'wrestler zodog costume', 'P2'],
     ['马头琴钥匙扣', 'morin khuur keychain', 'P2'],
     ['那达慕蓝色哈达', 'blue hadag silk', 'P2'],
     ['银鎏金头饰', 'mongolian silver headpiece', 'P3'],
     ['草原风马旗', 'tibetan prayer flags', 'P3'],
     ['羊毛毡杯垫', 'felt wool coasters', 'P3'],
     ['那达慕纪念徽章', 'naadam festival pin', 'P3']]],

  ['法国巴士底日', 'Bastille Day (14 Juillet)', '07-14', '07-14', 'EU',
    '法国国庆，纪念1789年攻占巴士底狱。巴黎香榭丽舍大街举行世界最大阅兵，战机喷出蓝白红三色烟幕；节日色彩为蓝白红，街头咖啡馆挂满三色灯笼与三角旗，消防员举办舞会，消防对开放参观；家庭在阳台挂国旗，傍晚到战神广场野餐，夜间埃菲尔铁塔下燃放盛大烟火，年轻人戴三色贝雷帽、脸贴国旗贴纸，全城派对持续到凌晨。',
    '蓝白红品类与多个欧洲市场通用，加入埃菲尔铁塔元素做法国专属溢价；贝雷帽、条纹衫等法式符号辨识度高。',
    [['法国三色国旗', 'france flag', 'P1'],
     ['蓝白红气球', 'blue white red balloons', 'P1'],
     ['国庆拉旗', 'bastille day banner', 'P1'],
     ['法式贝雷帽', 'french beret blue', 'P2'],
     ['国旗脸贴', 'french flag face stickers', 'P2'],
     ['埃菲尔铁塔摆件', 'eiffel tower decor', 'P2'],
     ['蓝白红腕带', 'france wristbands', 'P2'],
     ['条纹海魂衫', 'breton striped shirt', 'P3'],
     ['三色围巾', 'blue white red scarf', 'P3'],
     ['国庆糖果袋', 'france party favor bags', 'P3']]],

  ['哥伦比亚独立日', 'Colombian Independence Day', '07-20', '07-20', 'LATAM',
    '纪念1810年波哥大起义、迈向独立。波哥大举行阅兵与花车游行，节日色彩为国旗的黄、蓝、红，黄色占半幅最为醒目；街头挂满三色串旗与灯笼，人们戴黄蓝红假发与帽饰，孩子们穿三色校服参加学校游行；家庭餐桌上摆 Ajiaco 土豆鸡丝汤，酒吧供应朗姆鸡尾酒，晚间全城燃放烟火，广场有 Salsa 与 Vallenato 露天演唱会。',
    '黄蓝红三色与委内瑞拉/厄瓜多尔配色接近，加入哥伦比亚帽元素做区隔；Agudelo草帽周边是特色品类。',
    [['哥伦比亚国旗', 'colombia flag', 'P1'],
     ['黄蓝红气球', 'yellow blue red balloons', 'P1'],
     ['独立日拉旗', 'colombia independence banner', 'P2'],
     ['哥伦比亚草帽', 'colombian aguadas hat sombrero vueltiao', 'P2'],
     ['三色腕带', 'colombia wristbands', 'P2'],
     ['国旗披风', 'colombian flag cape', 'P2'],
     ['黄蓝红脸彩', 'yellow blue red face paint', 'P3'],
     ['手摇小旗套装', 'handheld colombian flags', 'P3'],
     ['三色花环项链', 'colombian flag lei', 'P3'],
     ['独立日礼品袋', 'colombia gift bags', 'P3']]],

  ['秘鲁独立日', 'Peruvian Fiestas Patrias', '07-28', '07-28', 'LATAM',
    '秘鲁国庆连庆两天：7月28日纪念1821年独立，29日为陆军节。利马举行总统主持的 Te Deum 弥撒与盛大阅兵，节日色彩为国旗的红与白，街头挂满红白双色旗与彩带；人们戴红白绒球帽，家里摆羊驼玩偶与马丘比丘模型，餐桌供应烤全豚鼠、Ceviche 酸橘腌鱼与紫玉米汁，晚间海滨燃放烟火，广场有安第斯排箫与瓦伊诺舞表演。',
    '红白配色与周边多国共享，羊驼、马丘比丘等秘鲁符号辨识度高；羊驼毛绒制品与民族风饰品客单可观。',
    [['秘鲁国旗', 'peru flag', 'P1'],
     ['红白气球', 'red white balloons peru', 'P1'],
     ['国庆拉旗', 'peru fiestas patrias banner', 'P2'],
     ['羊驼毛绒玩偶', 'alpaca stuffed animal', 'P2'],
     ['马丘比丘模型摆件', 'machu picchu decor', 'P2'],
     ['红白绒球帽', 'peruvian chullo hat', 'P2'],
     ['安第斯织带手绳', 'peruvian woven bracelet', 'P3'],
     ['国旗披风', 'peru flag cape', 'P3'],
     ['羊驼钥匙扣', 'alpaca keychain', 'P3'],
     ['国庆糖果袋', 'peru party favor bags', 'P3']]],

  ['瑞士国庆日', 'Swiss National Day', '08-01', '08-01', 'EU',
    '纪念1291年联邦永久同盟宪章，8月1日是瑞士国庆。节日色彩为国旗的红与白十字，阿尔卑斯山村在山顶点燃篝火，家家户户悬挂红底白十字国旗；人们穿传统服饰参加牛铃游行与合唱，面包师烤瑞士十字面包，农场举办早午餐，儿童提着纸灯笼夜游，湖边城镇燃放烟火倒映湖面，城镇广场分发免费登山早餐。',
    '红底白十字品类辨识度高，牛铃、纸灯笼与十字面包是特色；阿尔卑斯主题产品可与德国/奥地利南部市场共享。',
    [['瑞士国旗', 'switzerland flag', 'P1'],
     ['红白气球', 'red white balloons swiss', 'P1'],
     ['阿尔卑斯牛铃', 'swiss cow bell', 'P1'],
     ['国庆纸灯笼', 'swiss national lantern kids', 'P2'],
     ['白十字面包模具', 'swiss cross bread pan', 'P2'],
     ['国庆拉旗', 'swiss national day banner', 'P2'],
     ['红白腕带', 'swiss wristbands', 'P2'],
     ['白十字脸贴', 'swiss cross face stickers', 'P3'],
     ['埃门塔尔奶酪造型蜡烛', 'cheese shaped candle', 'P3'],
     ['国庆糖果袋', 'swiss favor bags', 'P3']]],

  ['巴基斯坦独立日', 'Pakistan Independence Day', '08-14', '08-14', 'ME',
    '纪念1947年8月14日巴基斯坦独立（比印度早一天）。节日主色为深绿与白，伊斯兰堡总统府举行升旗仪式，全国奏响 21 响礼炮；街头车辆挂满绿白旗与星月灯串，孩子们穿绿白衣服、戴星月发夹，脸涂绿色参加学校庆典，商场与地标打出绿色灯光秀，年轻人骑着装饰彩旗的摩托巡游，晚间各地燃放烟火。',
    '与3月巴基斯坦日共享品类，绿白星月供应链全年通用；脸彩、车旗与发光饰品在节前一周走量。',
    [['巴基斯坦手摇国旗', 'pakistan flag handheld', 'P1'],
     ['绿白气球', 'green white balloons pakistan', 'P1'],
     ['独立日车旗', 'pakistan car flags', 'P1'],
     ['星月拉旗', 'pakistan independence banner', 'P1'],
     ['绿色脸彩棒', 'green face paint', 'P2'],
     ['星月发光项链', 'crescent star light necklace', 'P2'],
     ['绿白假发', 'green white wig', 'P2'],
     ['绿白腕带', 'pakistan wristbands green', 'P2'],
     ['国旗造型太阳镜', 'green flag sunglasses', 'P3'],
     ['独立日糖果袋', 'pakistan favor bags', 'P3']]],

  ['乌克兰独立日', 'Ukrainian Independence Day', '08-24', '08-24', 'EU',
    '纪念1991年脱离苏联独立，8月24日是乌克兰最重要的国庆。基辅赫雷夏蒂克大街举行阅兵与装备展，节日主色为国旗的上蓝下黄，街道张挂蓝黄双色旗；人们佩戴蓝黄缎带与向日葵胸花，女青年编织花冠，民间歌手在广场演唱，住宅楼阳台挂满国旗，家庭餐桌上摆蓝黄配色蛋糕，傍晚全国为逝者默哀后燃放烟火。',
    '蓝黄配色品类辨识度极高，向日葵与刺绣 Vyshyvanka 纹样是民族符号；社会情绪复杂，设计庄重、突出和平与爱国主题。',
    [['乌克兰国旗', 'ukraine flag', 'P1'],
     ['蓝黄气球', 'blue yellow balloons', 'P1'],
     ['蓝黄缎带腕带', 'blue yellow ribbon wristband', 'P1'],
     ['向日葵胸花', 'sunflower pin brooch', 'P1'],
     ['独立日拉旗', 'ukraine independence banner', 'P2'],
     ['刺绣Vyshyvanka衫', 'vyshyvanka embroidered shirt', 'P2'],
     ['蓝黄花环头饰', 'blue yellow flower crown', 'P2'],
     ['国旗脸贴', 'ukraine flag face stickers', 'P2'],
     ['蓝黄灯串', 'blue yellow string lights', 'P3'],
     ['独立日糖果袋', 'ukraine favor bags', 'P3']]],

  ['番茄大战', 'La Tomatina', '08-26', '08-25', 'EU',
    '西班牙布尼奥尔小镇每年8月最后一个星期三的“世界最大食物大战”，上午11点卡车载着15吨熟番茄驶入广场，信号一响两万游客互相投掷番茄，全城化为红色番茄河；战前先有火腿杆攀爬热身，战后人们用街边水管互相冲洗，节日色彩为番茄红、酸橙绿与明黄，游客穿旧白T恤戴护目镜，酒吧供应 Sangría 与番茄面包。',
    '参战周边以防护与清洁用品为特色：护目镜、防水袋、白T恤套装；游客刚需且轻便，节前一周在西班牙站冲刺。',
    [['防溅护目镜', 'tomato fight goggles', 'P1'],
     ['防水手机袋', 'waterproof phone pouch', 'P1'],
     ['番茄战白T恤', 'la tomatina t shirt', 'P1'],
     ['番茄红气球', 'red balloons party', 'P2'],
     ['番茄造型帽子', 'tomato novelty hat', 'P2'],
     ['便携洗漱毛巾', 'quick dry microfiber towel', 'P2'],
     ['防水背包套', 'waterproof backpack cover', 'P2'],
     ['番茄战贴纸', 'la tomatina stickers', 'P3'],
     ['红色腕带', 'red wristbands', 'P3'],
     ['番茄纪念徽章', 'tomatina souvenir pin', 'P3']]],

  ['火人节', 'Burning Man', '08-30', '08-29', 'NA',
    '美国内华达黑石沙漠的反传统狂欢，每年劳工节前的周日开幕、持续8天，最后一夜焚烧巨型木人。节日没有官方色彩，但荧光色、金属色与沙漠裸色系是主流：人们穿皮草大衣配荧光腿套、护目镜防尘，营地布满 LED 发光雕塑与艺术车；白天参加瑜伽与 DJ 派对，夜晚骑车挂满彩灯穿梭，人们互赠“礼物经济”手工，灰烬散去后不留一片垃圾。',
    '节日穿搭是 TikTok 爆款话题：护目镜、发光配饰、沙漠靴与皮草大衣周边需求集中；设计越夸张越好卖，提前60天上架。',
    [['防风沙护目镜', 'burning man goggles dust', 'P1'],
     ['LED发光腿套', 'led light leg warmers', 'P1'],
     ['荧光色假发', 'neon rave wig', 'P1'],
     ['迷彩防尘头巾', 'dust mask bandana', 'P1'],
     ['EL发光线身体配饰', 'el wire body suit', 'P2'],
     ['沙漠绑带靴套', 'desert boot covers', 'P2'],
     ['自行车彩灯轮', 'led bike wheel lights', 'P2'],
     ['仿皮草短外套', 'faux fur coat rave', 'P2'],
     ['荧光太阳镜', 'neon sunglasses reflective', 'P3'],
     ['水袋背包', 'hydration pack backpack', 'P3']]],

  ['犹太新年', 'Rosh Hashanah', '09-12', '10-02', 'ME',
    '犹太教岁首，为期两天，纪念创世，随后十天忏悔直到赎罪日。节日色彩为白、金、深紫与石榴红，会堂吹响羊角号 Shofar；晚餐餐桌上摆蘸蜜的苹果片、石榴、圆形 Challah 辫子面包，寓意甜蜜新年；人们穿白色新衣，家中挂“Shanah Tovah”金色拉旗，给亲友寄送新年贺卡，餐桌中央摆蜂蜜罐与蜂巢装饰，鱼头等吉祥菜不可少。',
    '羊角号、蜂蜜餐具与石榴周边是节日特色，金色系装饰与光明节供应链通用；面向以色列与北美犹太社区提前45天备货。',
    [['羊角号摆件', 'shofar ram horn', 'P1'],
     ['蜂蜜罐与蘸盘', 'rosh hashanah honey dish', 'P1'],
     ['石榴造型餐盘', 'pomegranate plate decor', 'P1'],
     ['新年金色拉旗', 'shanah tovah banner', 'P1'],
     ['圆形辫子面包罩', 'challah cover cloth', 'P2'],
     ['白色祈祷披巾', 'white kittel robe', 'P2'],
     ['苹果切片器', 'apple slicer corer', 'P2'],
     ['新年贺卡套装', 'jewish new year cards', 'P2'],
     ['金白气球', 'gold white balloons', 'P3'],
     ['石榴串灯', 'pomegranate string lights', 'P3']]],

  ['马来西亚日', 'Malaysia Day (Hari Malaysia)', '09-16', '09-16', 'SEA',
    '纪念1963年马来亚、沙巴、砂拉越与新加坡组成马来西亚联邦（新加坡后来退出），9月16日是全国公共假日。吉隆坡举行盛大游行与文艺演出，节日色彩丰富，以辉煌条纹旗的蓝、黄、红、白为主；街头挂起红白条纹旗与各族旗帜，学生手持小旗游行，商场布置多元民族主题展，家庭团聚吃椰浆饭与肉骨茶，东马沙巴砂拉越还有达雅族传统舞蹈。',
    '与8月底国庆（独立日）相距半月、形成二次备货；国旗条纹元素与多元民族服饰为主推，主打东马本地仓。',
    [['马来西亚辉煌条纹旗', 'malaysia flag jalur gemilang', 'P1'],
     ['彩色气球套装', 'colorful balloons malaysia', 'P1'],
     ['马来西亚日拉旗', 'hari malaysia banner', 'P2'],
     ['手摇小旗套装', 'handheld malaysian flags', 'P2'],
     ['新月星月徽章', 'malaysian crescent pin', 'P2'],
     ['蜡染Batik丝巾', 'malaysian batik scarf', 'P2'],
     ['彩色腕带', 'malaysia wristbands colorful', 'P3'],
     ['红蓝黄桌旗', 'malaysia table runner', 'P3'],
     ['民族风钥匙扣', 'wau bulan kite keychain', 'P3'],
     ['马来西亚日糖果袋', 'malaysia favor bags', 'P3']]],

  ['住棚节', 'Sukkot (Feast of Tabernacles)', '09-26', '10-16', 'ME',
    '犹太教三大朝圣节之一，纪念出埃及时在旷野住棚，节期7天（以色列）至8天（海外）。人们在庭院或阳台搭建 Sukkah 棚舍，以木架布围、屋顶铺修剪过的树枝，可看见星空；全家在棚下吃饭待客，节日色彩为橄榄绿、丰收橙、金色与深紫，棚内挂水果串与丰收装饰，男士手持 Lulav 棕榈枝束与 Etrog 香柠檬做祈祷，末日后紧接着诵经节 Simchat Torah 欢舞。',
    '棚舍搭建材料与丰收装饰是节日刚需，水果挂串、棕榈枝周边为特色品类；大件棚架走本地仓，装饰小物走跨境。',
    [['住棚节棚布围', 'sukkah decorations walls', 'P1'],
     ['水果丰收挂串', 'sukkot fruit garland', 'P1'],
     ['棕榈枝束套装', 'lulav and etrog set', 'P1'],
     ['棚内串灯', 'sukkah string lights outdoor', 'P1'],
     ['丰收主题拉旗', 'sukkot banner', 'P2'],
     ['橄榄绿桌布', 'green tablecloth outdoor', 'P2'],
     ['水果造型灯笼', 'fruit paper lanterns', 'P2'],
     ['棚舍固定夹套装', 'sukkah clips bamboo', 'P2'],
     ['丰收玉米装饰', 'corn husk decorations', 'P3'],
     ['住棚节贺卡', 'sukkot greeting cards', 'P3']]],

  ['德国统一日', 'German Unity Day (Tag der Deutschen Einheit)', '10-03', '10-03', 'EU',
    '纪念1990年10月3日东西德统一，是德国现代国庆。庆祝城市每年轮换主办，举行联邦各州庆典博览会与总统招待会，节日色彩为黑、红、金三色；街头悬挂三色旗，柏林勃兰登堡门举办露天市民节，人们穿日常装手持小旗，面包师烤黑红金三色蛋糕，广场有摇滚乐队演出与脱口秀，各党派发放气球与旗帜，晚间在施普雷河畔放烟火。',
    '黑红金三色品类与比利时/埃及等市场配色相近，加入勃兰登堡门或联邦鹰元素做区隔；客单轻松日常为主。',
    [['德国国旗', 'germany flag', 'P1'],
     ['黑红金气球', 'black red gold balloons', 'P1'],
     ['统一日拉旗', 'german unity banner', 'P2'],
     ['手摇小旗套装', 'handheld german flags', 'P2'],
     ['联邦鹰胸针', 'german federal eagle pin', 'P2'],
     ['三色腕带', 'germany wristbands', 'P2'],
     ['啤酒杯造型周边', 'german beer stein mug', 'P3'],
     ['三色围巾', 'black red gold scarf', 'P3'],
     ['国旗脸贴', 'german flag face stickers', 'P3'],
     ['统一日糖果袋', 'germany favor bags', 'P3']]],

  ['西班牙国庆', 'Spain National Day (Fiesta Nacional / Día de la Hispanidad)', '10-12', '10-12', 'EU',
    '10月12日西班牙国庆，纪念1492年哥伦布抵达美洲，也纪念西班牙语世界同源。马德里阅兵由国王主持，三军仪仗与战机拉着红黄两色烟带通过；节日色彩为国旗的红与黄，街头悬挂红黄双色旗与国徽旗，马德里王宫升起巨型国旗，人们佩戴红黄腕带，酒吧供应海鲜饭与桑格利亚，海外拉美裔社区也共同庆祝“西语日”，晚间广场有弗拉门戈演出。',
    '红黄色品类与拉美市场供应链相通，加入斗牛士、吉他等符号做西班牙特色；轻便饰品与国旗T恤走量。',
    [['西班牙国旗', 'spain flag', 'P1'],
     ['红黄色气球', 'red yellow balloons', 'P1'],
     ['国庆拉旗', 'spain national day banner', 'P2'],
     ['弗拉门戈折扇', 'flamenco hand fan', 'P2'],
     ['红黄腕带', 'spain wristbands', 'P2'],
     ['斗牛士帽', 'matador hat costume', 'P2'],
     ['手摇小旗套装', 'handheld spanish flags', 'P3'],
     ['红黄围巾', 'red yellow scarf spain', 'P3'],
     ['西班牙吉他钥匙扣', 'spanish guitar keychain', 'P3'],
     ['国庆糖果袋', 'spain favor bags', 'P3']]],

  ['土耳其共和国日', 'Turkey Republic Day (29 Ekim)', '10-29', '10-29', 'ME',
    '纪念1923年10月29日土耳其共和国宣告成立、国父凯末尔就任首任总统。安卡拉阿尼特卡比尔陵寝举行献花仪式，伊斯坦布尔博斯普鲁斯海峡两岸举行盛大烟火与无人机灯光秀；节日色彩为国旗的红与白，街头与阳台上红旗招展，人们在脸上画星月、举火炬游行，孩子们朗诵 Atatürk 诗歌，家庭餐桌摆烤肉与 Baklava 果仁蜜饼，晚间轮船鸣汽笛庆祝。',
    '红白星月品类与多个穆斯林市场通用，但加入凯末尔签名/语录元素是土耳其专属；国旗大件走本地仓，脸彩小物走跨境。',
    [['土耳其国旗', 'turkey flag', 'P1'],
     ['红白气球', 'red white balloons turkey', 'P1'],
     ['星月脸彩贴', 'turkish crescent face stickers', 'P1'],
     ['共和国日拉旗', '29 ekim banner', 'P1'],
     ['凯末尔签名胸针', 'atatürk signature pin', 'P2'],
     ['红白腕带', 'turkey wristbands red', 'P2'],
     ['星月发光棒', 'crescent led light stick', 'P2'],
     ['红白围巾', 'turkish flag scarf', 'P2'],
     ['手摇小旗套装', 'handheld turkish flags', 'P3'],
     ['国庆糖果袋', 'turkey favor bags', 'P3']]],

  ['诸圣节', 'All Saints’ Day (Toussaint)', '11-01', '11-01', 'EU',
    '天主教与圣公会纪念所有圣徒的节日，11月1日在法国、意大利、波兰、西班牙等国是公共假日，次日2日为追思已亡节。节日色彩肃穆，以白、深紫与菊花黄为主，全家携带白菊花束与长明墓前灯祭扫公墓，擦拭墓碑、点燃玻璃防风蜡烛；教堂举行追思弥撒、钟楼长鸣，家中摆圣徒像与白色蜡烛，餐桌只上简朴的炖菜，商店菊花专柜前人流如织。',
    '与万圣节娱乐主题完全不同：墓前防风蜡烛、仿真白菊花为刚需；玻璃电子蜡烛安全款在欧洲城市公墓接受度高。',
    [['墓地防风蜡烛', 'grave candles cemetery', 'P1'],
     ['白菊花束仿真', 'white chrysanthemums artificial', 'P1'],
     ['电子墓前灯', 'led memorial candle grave', 'P1'],
     ['深紫色弥撒纱带', 'purple memorial ribbon', 'P2'],
     ['诸圣节拉旗', 'all saints day banner', 'P2'],
     ['圣徒画像摆件', 'all saints icon catholic', 'P2'],
     ['白色蜡烛花环', 'white candle wreath', 'P2'],
     ['墓地花艺插架', 'grave flower holder', 'P3'],
     ['追思贺卡', 'all souls mass card', 'P3'],
     ['深紫腕带', 'purple wristbands', 'P3']]],

  ['墨西哥革命纪念日', 'Mexican Revolution Day', '11-16', '11-15', 'LATAM',
    '纪念1910年墨西哥革命爆发，官方庆典定在11月第三个星期一（原为11月20日）。墨西哥城改革大道举行盛大阅兵与骑兵游行，节日色彩为国旗的绿、白、红，街头悬挂三色旗；孩子们戴 Pancho Villa 式宽边帽、贴小胡子参加学校历史剧，社区举办革命主题展览，家庭餐桌摆 Mole 酱鸡与玉米粽，广场有 Mariachi 街头乐队与民俗舞表演，晚间燃放烟火。',
    '爱国主题品类与9月独立日通用，宽边帽、小胡子等装扮道具在儿童市场走量；节后可衔接亡灵节余温做联动营销。',
    [['墨西哥宽边帽', 'mexican sombrero hat', 'P1'],
     ['绿白红气球', 'green white red balloons mexico', 'P1'],
     ['革命日拉旗', 'mexican revolution banner', 'P2'],
     ['Pancho小胡子道具', 'fake mustache costume', 'P2'],
     ['三色绶带', 'mexican tricolor sash', 'P2'],
     ['革命主题T恤', 'mexican revolution t shirt', 'P2'],
     ['手摇小旗套装', 'handheld mexican flags', 'P3'],
     ['三色腕带', 'mexico wristbands', 'P3'],
     ['鹰蛇徽章', 'mexican eagle pin', 'P3'],
     ['革命日糖果袋', 'mexico favor bags', 'P3']]],

  ['阿曼国庆', 'Oman National Day', '11-18', '11-18', 'ME',
    '阿曼苏丹国国庆，庆祝卡布斯苏丹开创现代阿曼，11月18日起连庆两天。马斯喀特大街小巷张灯结彩，以国旗的红、白、绿三色与苏丹徽章为主题，政府大楼灯光秀彻夜通明；人们穿传统白色 Dishdasha 长袍、佩戴 Khanjar 弯刃匕首参加游行，骆驼与马队披红挂彩，商场举办民俗展，家庭在沙漠营地野餐，晚间海湾上空燃放烟火，孩子们挥舞小旗。',
    '海湾高客单市场，Khanjar匕首造型饰品与红白绿装饰为特色；竞争卖家少，适合提前布局做差异化。',
    [['阿曼国旗', 'oman flag', 'P1'],
     ['红白绿气球', 'red white green balloons oman', 'P1'],
     ['国庆拉旗', 'oman national day banner', 'P2'],
     ['Khanjar匕首胸针', 'khanjar dagger pin', 'P2'],
     ['苏丹纪念徽章', 'oman sultan pin badge', 'P2'],
     ['红白绿腕带', 'oman wristbands', 'P2'],
     ['传统香炉', 'omani frankincense burner', 'P3'],
     ['手摇小旗套装', 'handheld omani flags', 'P3'],
     ['弯刃匕首造型钥匙扣', 'khanjar keychain', 'P3'],
     ['国庆糖果袋', 'oman favor bags', 'P3']]],

  ['巴西黑人意识日', 'Black Consciousness Day (Consciência Negra)', '11-20', '11-20', 'LATAM',
    '巴西纪念非裔文化与 Zumbi dos Palmares 反抗奴隶制的纪念日，11月20日在圣保罗、里约等州为公共假日。节日色彩以非洲风情的绿、黄、红、黑为主，萨尔瓦多与里约举行 Samba 鼓乐巡游与 Capoeira 武术表演；人们穿非洲印花蜡染衫、戴头巾珠饰，学校开设非裔历史课，社区供应 Feijoada 黑豆炖肉，广场有 Candomblé 宗教仪式与集市，青年举“黑人生命重要”标语游行。',
    '非裔文化主题小众但竞争小，非洲印花服饰、头巾与鼓类乐器为主推；设计尊重文化根源，避免刻板元素。',
    [['非洲印花头巾', 'african head wrap ankara', 'P1'],
     ['蜡染印花连衣裙', 'african wax print dress', 'P1'],
     ['Samba小手鼓', 'samba drum brazilian', 'P2'],
     ['部落风串珠项链', 'tribal bead necklace', 'P2'],
     ['黑红绿气球', 'black red green balloons', 'P2'],
     ['Capoeira武术裤', 'capoeira pants white', 'P2'],
     ['非洲风耳环', 'ankara fabric earrings', 'P3'],
     ['羽毛头饰', 'african feather headpiece', 'P3'],
     ['部落风腕带', 'tribal wristbands', 'P3'],
     ['文化主题贴纸', 'black consciousness stickers', 'P3']]],

  ['光明节', 'Hanukkah (Chanukah)', '12-05', '12-25', 'ME',
    '犹太修殿节，纪念马卡比起义后圣殿油灯奇迹（仅够一天的油燃了八天），连续庆祝八夜，每夜多点一支蜡烛，第九支 Shamash 用来引火。节日色彩为蓝、白、金，家中摆放九枝烛台 Hanukkiah，全家围坐吃土豆 Latke 饼与果酱 Sufganiyot 甜甜圈；孩子们玩旋转陀螺 Dreidel、收巧克力金币礼物，门窗挂蓝色串灯，客厅摆烛台造型抱枕，亲友来家参加点灯派对。',
    '九枝烛台、陀螺与巧克力金币网袋是节日刚需，蓝白金品类与其他犹太节共享；蜡烛安全款与电子烛台更受有孩家庭欢迎。',
    [['九枝光明烛台', 'hanukkah menorah', 'P1'],
     ['彩色旋转陀螺', 'wooden dreidel set', 'P1'],
     ['土豆饼煎锅', 'latke frying pan', 'P1'],
     ['光明节蓝白拉旗', 'happy hanukkah banner', 'P1'],
     ['巧克力金币网袋', 'gold chocolate coins bags', 'P2'],
     ['甜甜圈果酱模具', 'sufganiyot donut cutter', 'P2'],
     ['蓝色串灯', 'blue white string lights', 'P2'],
     ['烛台造型餐具', 'menorah paper plates', 'P2'],
     ['光明节贺卡', 'hanukkah greeting cards', 'P3'],
     ['儿童礼物盲盒', 'hanukkah gift boxes kids', 'P3']]],

  ['圣露西亚节', 'Saint Lucy’s Day (Lucia)', '12-13', '12-13', 'EU',
    '北欧黑暗冬季的烛光节日，纪念三世纪殉道圣女露西亚，12月13日在瑞典、挪威、芬兰、丹麦庆祝。清晨家中女孩扮成 Lucia：穿白色长袍、腰间系红丝带、头戴插着蜡烛的绿叶冠，手捧藏红花面包 Singing 走进父母卧室；节日色彩为白、烛光金与圣诞红，学校与教堂举行 Lucia 唱诗游行，咖啡馆供应藏红花小面包与热红酒，烛冠与纸灯笼照亮漫长冬夜。',
    '烛冠头饰与白袍红丝带套装是儿童刚需，藏红花面包模具与烛光装饰为主推；与圣诞季供应链完全通用。',
    [['Lucia烛光发冠', 'saint lucia candle crown', 'P1'],
     ['白色儿童长袍', 'lucia white gown girls', 'P1'],
     ['红色丝带腰带', 'red ribbon sash', 'P1'],
     ['绿叶头环', 'advent green head wreath', 'P2'],
     ['藏红花面包模具', 'saffron bun baking pan', 'P2'],
     ['手持电子蜡烛', 'led taper candles set', 'P2'],
     ['圣露西亚节拉旗', 'sankta lucia banner', 'P2'],
     ['白色长筒袜', 'white tights girls', 'P3'],
     ['星星男孩魔杖', 'star boy wand costume', 'P3'],
     ['烛光纸灯笼', 'paper lantern candle', 'P3']]],

  ['卡塔尔国庆', 'Qatar National Day', '12-18', '12-18', 'ME',
    '卡塔尔国庆纪念1878年贾西姆·本·穆罕默德·阿勒萨尼统一半岛建国，12月18日多哈全城大庆。节日主色为栗色（国旗独有色）与白，滨海大道举行阅兵、传统骆驼马队游行与 Dhau 帆船表演；街头悬挂栗白双色国旗与 Sword 弯刀徽章，人们穿栗色服饰，儿童画脸，独桅帆船张灯，晚间有盛大烟火与无人机表演，家庭在沙漠帐篷里喝咖啡、吃 Machbous 香料饭。',
    '栗白配色在全球国旗中独一无二、极易做出辨识度；弯刀徽章、独桅帆船造型饰品为特色，海湾客单高。',
    [['卡塔尔国旗', 'qatar flag', 'P1'],
     ['栗白气球', 'maroon white balloons', 'P1'],
     ['国庆拉旗', 'qatar national day banner', 'P1'],
     ['弯刀徽章胸针', 'qatar sword emblem pin', 'P2'],
     ['栗色脸彩棒', 'maroon face paint', 'P2'],
     ['独桅帆船模型', 'dhow boat model decor', 'P2'],
     ['栗白腕带', 'qatar wristbands maroon', 'P2'],
     ['栗色头巾', 'maroon scarf men', 'P3'],
     ['国庆电子蜡烛', 'led candle maroon', 'P3'],
     ['国庆糖果袋', 'qatar favor bags', 'P3']]],

  ['宽扎节', 'Kwanzaa', '12-26', '12-26', 'NA',
    '非裔美国人的文化节日，12月26日至1月1日连庆七天，纪念非洲传统与家庭价值，每天点燃 Kinara 七枝烛台中的一支（三支红、三支绿、中间黑烛）。节日色彩为红、黑、绿，家中铺 Mkeka 草编席，摆 Mazao 果盘、Unity Cup 团结杯与玉米穗；全家轮流讲七项原则（团结、自决、集体劳动等），互换手工礼物，最后夜 Karamu 非洲盛宴，鼓声与舞会通宵。',
    '文化属性强、用户忠诚度高，Kinara烛台、Mkeka草席与七原则挂画是刚需；竞争远小于圣诞，适合做长期长青链接。',
    [['七枝烛台Kinara', 'kwanzaa kinara candle holder', 'P1'],
     ['Mkeka草编桌垫', 'mkeka kwanzaa placemat', 'P1'],
     ['团结杯摆件', 'unity cup kikombe', 'P1'],
     ['七原则挂画', 'kwanzaa seven principles poster', 'P2'],
     ['红绿黑蜡烛套装', 'kwanzaa candles mishumaa', 'P2'],
     ['非洲鼓小手鼓', 'djembe drum small', 'P2'],
     ['玉米穗装饰', 'kwanzaa muhindi corn decor', 'P2'],
     ['宽扎节拉旗', 'happy kwanzaa banner', 'P3'],
     ['非洲串珠手环', 'african bead bracelet', 'P3'],
     ['宽扎节礼品袋', 'kwanzaa gift bags', 'P3']]],
];

function esc(value) {
  return String(value).replaceAll("'", "''");
}

const years = [2026, 2027];
let festivalId = 0;
let goodsId = 0;
const festivalRows = [];
const goodsRows = [];

FESTIVALS.forEach((entry) => {
  const [name, enName, date2026, date2027, regions, intro, advice, goods] = entry;

  if (goods.length < MIN_GOODS_PER_FESTIVAL) {
    throw new Error(`节日「${name}」商品仅 ${goods.length} 件，至少需要 ${MIN_GOODS_PER_FESTIVAL} 件`);
  }

  const dates = { 2026: date2026, 2027: date2027 };

  years.forEach((year) => {
    festivalId += 1;
    const currentFestivalId = festivalId;
    festivalRows.push(
      `(${currentFestivalId},'${esc(name)}','${esc(enName)}','${year}-${dates[year]}',${year},'${esc(regions)}','${esc(intro)}','${esc(advice)}')`,
    );

    goods.forEach((item, index) => {
      const [goodsName, enKeyword, priority] = item;
      const yearlyKeyword = enKeyword.replaceAll('{YEAR}', String(year));
      goodsId += 1;
      const sortOrder = (index + 1) * 10;
      goodsRows.push(
        `(${goodsId},${currentFestivalId},'${esc(goodsName)}','${esc(yearlyKeyword)}','${priority}',${sortOrder})`,
      );
    });
  });
});

const sql = `-- 由 db/tools/generate-seed.mjs 自动生成，请勿手工修改（PostgreSQL）
TRUNCATE festival_goods, festival RESTART IDENTITY CASCADE;

INSERT INTO festival (id, name, en_name, festival_date, year, regions, intro, advice) VALUES
${festivalRows.join(',\n')};

INSERT INTO festival_goods (id, festival_id, goods_name, en_keyword, priority, sort_order) VALUES
${goodsRows.join(',\n')};

-- 重置序列到 max(id)+1（显式 id 插入后 pg 序列不会自动推进）
SELECT setval(pg_get_serial_sequence('festival', 'id'), (SELECT MAX(id) FROM festival));
SELECT setval(pg_get_serial_sequence('festival_goods', 'id'), (SELECT MAX(id) FROM festival_goods));
`;

const here = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(here, '..', 'init', '02_seed.sql');
writeFileSync(outputPath, sql, 'utf8');
console.log(`已生成 ${outputPath}`);
console.log(`节日 ${festivalId} 条（${FESTIVALS.length} 个节日 × 2 年），商品 ${goodsId} 条。`);
